<?php

    define('PUBLICATIONS_STATE_DELETED',0);
    define('PUBLICATIONS_STATE_INACTIVE',1);
    define('PUBLICATIONS_STATE_SUBMITTED',1);
    define('PUBLICATIONS_STATE_DRAFT',2);
    define('PUBLICATIONS_STATE_ONHOLD',2);
    define('PUBLICATIONS_STATE_ACTIVE',3);
    define('PUBLICATIONS_STATE_APPROVED',3);
    define('PUBLICATIONS_STATE_FRONTPAGE',4);
    define('PUBLICATIONS_STATE_CHECKEDOUT',4);

?>
