<?php

/**
 * list polls
 */
function polls_user_list()
{
    // Get input parameters
    $startnum = xarVarCleanFromInput('startnum');

    // Security check - important to do this as early as possible to avoid
    // potential security holes or just too much wasted processing
    if(!xarSecurityCheck('ListPolls')){
        return;
    }

    // The API function is called.  The arguments to the function are passed in
    // as their own arguments array
    $items = xarModAPIFunc('polls',
                          'user',
                          'getall',
                          array('startnum' => $startnum,
                                'numitems' => xarModGetVar('polls',
                                                          'itemsperpage')));
    $data = array();
    if (!$items) {
        return $data;
    }

    $data = array();

    // The return value of the function is checked here, and if the function
    // suceeded then an appropriate message is posted.  Note that if the
    // function did not succeed then the API function should have already
    // posted a failure message so no action is required

    $data['previewresults'] = xarModGetVar('polls', 'previewresults');
    $data['polls'] = array();
    // TODO - loop through each item and display it
    foreach ($items as $item) {
        $poll = array();

        $poll['title'] = $item['title'];
        $poll['type'] = $item['type'];
        $poll['private'] = $item['private'];
        $poll['votes'] = $item['votes'];
        if($item['open'] == '1'){
            $poll['open'] = 1;
        }
        else {
            $poll['open'] = 0;
        }
        $poll['canvote'] = xarModAPIFunc('polls',
                                 'user',
                                 'usercanvote',
                                 array('pid' => $item['pid']));


        $poll['action_vote'] = xarModURL('polls', 'user', 'display',
                               array('pid' => $item['pid']));
        $poll['action_results'] = xarModURL('polls', 'user', 'results',
                                  array('pid' => $item['pid']));

        $data['polls'][] = $poll;
    }

    // Call pager
/*    $output->Pager($startnum,
            xarModAPIFunc('polls', 'user', 'countitems'),
                         xarModURL('polls',
                                  'user',
                                  'list',
                                  array('startnum' => '%%')),
                         xarModGetVar('polls', 'itemsperpage'));
*/
    // Return the output that has been generated by this function
    return $data;
}

?>