<?php
/**
 * Helpdesk Module
 *
 * @package modules
 * @copyright (C) 2002-2006 The Digital Development Foundation
 * @license GPL {@link http://www.gnu.org/licenses/gpl.html}
 * @link http://www.xaraya.com
 *
 * @subpackage Helpdesk Module
 * @link http://www.abraisontechnoloy.com/
 * @author Brian McGilligan <brianmcgilligan@gmail.com>
 */
/**
   This is a standard function to modify the configuration parameters of the
   module

   @return template data
*/
function helpdesk_admin_modifyconfig()
{
    // Security check - important to do this as early as possible to avoid
    // potential security holes or just too much wasted processing
    if( !Security::check(SECURITY_ADMIN, 'helpdesk') ){ return false; }


    if( !xarModAPILoad('helpdesk') ){ return false; }

    // Add menu to output - it helps if all of the module pages have a standard
    // menu at their head to aid in navigation
    $data['menutitle'] = xarModAPIFunc('helpdesk', 'admin', 'menu');

    // Add an authorisation ID - this adds a hidden field in the form that
    // contains an authorisation ID.  The authorisation ID is very important in
    // preventing certain attacks on the website
    $data['authid'] = xarSecGenAuthKey();

    $data['statuses'] = "xarModAPIFunc('helpdesk', 'user', 'gets',
        array(
            'keyvalue' => true,
            'itemtype' => STATUS_ITEMTYPE
        )
    );";

    if( !xarVarFetch('itemtype', 'int', $itemtype, TICKET_ITEMTYPE, XARVAR_NOT_REQUIRED) ){ return; }

    $data['hooks'] = xarModCallHooks('module', 'modifyconfig', 'helpdesk',
        array(
            'module'   => 'helpdesk',
            'itemtype' => $itemtype
        )
    );

    // Return the output that has been generated by this function
    return $data;
}
?>
