-- phpMyAdmin SQL Dump
-- version 2.8.0
-- http://www.phpmyadmin.net
-- 
-- Host: localhost
-- Generation Time: Apr 29, 2007 at 09:44 AM
-- Server version: 4.1.20
-- PHP Version: 4.3.9
-- 
-- Database: `xaraya1`
-- 

-- --------------------------------------------------------

-- 
-- Table structure for table `xar_ievents_events`
-- 

CREATE TABLE `xar_ievents_events` (
  `eid` int(11) NOT NULL auto_increment,
  `calendar_id` int(11) NOT NULL default '0',
  `title` varchar(255) NOT NULL default '',
  `status` varchar(10) NOT NULL default 'DRAFT',
  `created_time` int(11) NOT NULL default '0',
  `updated_time` int(11) NOT NULL default '0',
  `created_by` int(11) NOT NULL default '0',
  `updated_by` int(11) NOT NULL default '0',
  `all_day` char(1) NOT NULL default 'A',
  `start_date` int(11) NOT NULL default '0',
  `end_date` int(11) default NULL,
  `summary` text,
  `description` text,
  `url` varchar(255) default NULL,
  `external_source` varchar(100) default NULL,
  `external_ref` varchar(100) default NULL,
  `flags` varchar(100) default NULL,
  `location_venue` varchar(255) default NULL,
  `location_address` text,
  `location_country` varchar(200) default NULL,
  `location_postcode` varchar(20) default NULL,
  `contact_email` varchar(200) default NULL,
  `contact_phone` varchar(60) default NULL,
  `contact_details` text,
  `cost` varchar(255) default NULL,
  `locks` varchar(10) NOT NULL default '',
  PRIMARY KEY  (`eid`),
  KEY `calendar_id` (`calendar_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=59 ;

-- 
-- Dumping data for table `xar_ievents_events`
-- 

INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (1, 1, 'First event', 'ACTIVE', 1177346647, 1177346647, 3, 3, 'A', 1177346647, 1177346647, '<h1>Summary</h1>\r\n<p>sdfasdfas d\r\n\r\n&amp; sadf &&&&four ', 'Detail.\r\n\r\nOn a second line,\r\nwith a close line.\r\n\r\nAnd another paragraph.', '', 'J''J', '', 'F,T', NULL, '', '', '', '', '', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (2, 1, 'Second event', 'ACTIVE', 1177346660, 1177346660, 3, 3, 'A', 1177346660, 1177346760, 'sdfgs gsdfg asdfs df asd fas d fasdfasdk s dlkasdfkas dklfasdjf asdjf sakdjfaskdfklasd kfsiodufiouio isid ioasdofusdio sfi sudofasodfisuf', 's dgfsfdgsdfg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', '', '', NULL, NULL);
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (3, 0, '', 'DRAFT', 0, 0, 0, 0, 'A', 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', '', '', NULL, NULL);
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (4, 1, 'Convocation', 'ACTIVE', 1177681011, 1177681011, 3, 3, 'A', 1157711400, 0, '', 'Students, faculty, and staff will mark the start of Mount Holyoke''s 170th academic year. A community picnic on Skinner Green will follow the ceremony.', '', '', '', '', NULL, 'Gettell Amphitheatre (Chapin Auditorium in case of rain)', '', '', 'psilvier@mtholyoke.edu', '2663', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (5, 1, 'Jhumka Dance Team Tryouts', 'ACTIVE', 1177681039, 1177681039, 3, 3, 'A', 1157983200, 0, '', '', '', '', '', '', NULL, 'Mary Woolley Hall, Chapin Auditorium', '', '', '', '571-232-2092', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (6, 1, 'Gender Free Contra Dance', 'ACTIVE', 1177681039, 1177681039, 3, 3, 'A', 1158690600, 0, '', '', '', '', '', '', NULL, 'Blanchard Campus Center, Great Room and Balcony', '', '', 'mrmoon@mtholyoke.edu', '', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (7, 1, 'SIZZLIN', 'ACTIVE', 1177681039, 1177681039, 3, 3, 'A', 1159822800, 0, '', '', '', '', '', '', NULL, 'Blanchard Campus Center, Great Room and Balcony', '', '', '', '2459', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (8, 1, 'Community Breakfast', 'ACTIVE', 1177681039, 1177681039, 3, 3, 'A', 1160204400, 0, '', 'President Joanne V. Creighton and the senior staff invite students, faculty, and staff to join them for an informal continental breakfast and good conversation.', '', '', '', '', NULL, 'Blanchard Campus Center', '', '', '', '2464', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (9, 1, 'Temptasian', 'ACTIVE', 1177681039, 1177681039, 3, 3, 'A', 1160254800, 0, '', '', '', '', '', '', NULL, 'Blanchard Campus Center, Great Room and Balcony', '', '', 'mhc.jhumka@gmail.com', '240-353-0561', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (10, 1, 'The New England Women''s Conference on Global Finance and Business', 'ACTIVE', 1177681039, 1177681039, 3, 3, 'A', 1177977600, 1177977600, 'YYNA', 'The New England Women''s Conference on Global Finance and Business presented by the Lyons Network focuses on opening opportunities for professional success and leadership in the field of global fiance and business for undergraduate women. The conference is sponsored by JP Morgan Chase, Goldman Sachs, Credit Suisse, and 85 Broads. Undergraduate women from 30 liberal arts colleges and 20 universities across the Northeast will participate.', '', '', '', '', NULL, 'Gamble Auditorium', '', '', 'registration@thelyonsnetwork.org', '', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (11, 1, 'MHACASA Signature Dance: The Electric Slide', 'ACTIVE', 1177681039, 1177681039, 3, 3, 'T', 1177977600, 1177977600, 'YYNT', '', '', '', '', '', NULL, 'Blanchard Campus Center, Steps (Facing Skinner Green)', '', '', 'tsmalcol', '8866', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (12, 1, 'The Hartford-Springfield Economic Partnership Third Annual College Career Expo', 'ACTIVE', 1177681039, 1177681039, 3, 3, 'A', 1177977600, 1178020800, 'YNNA', 'Please check www.collegecareerexpo.com for more information', '', '', '', '', NULL, 'Rentschler Field, East Hartford', '', '', '', '2080', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (13, 1, 'Fusion Fever', 'ACTIVE', 1177681039, 1177681039, 3, 3, 'T', 1177977600, 1178020800, 'YNNT', '', '', '', '', '', NULL, 'Blanchard Campus Center, Great Room and Balcony', '', '', 'anwar20f@mtholyoke.edu', '240-353-0561', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (14, 1, 'Legacies of Leadership: A Student Conference', 'ACTIVE', 1177681039, 1177681039, 3, 3, 'A', 1177977600, 1178150400, 'NNNA', 'MHC students are invited to attend a day of engaging workshops and inspiring discussion about personal leadership and success.', '', '', '', '', NULL, 'Willits-Hallowell Center', '', '', 'wcl@mtholyoke.edu', '3071', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (15, 1, 'American Ballet Theatre Studio Company', 'ACTIVE', 1177681039, 1177681039, 3, 3, 'T', 1177977600, 1178150400, 'NNNT', 'On Saturday, December 9, a 2 pm performance will also be offered.', '', '', '', '', NULL, 'Studio Theater/Kendall', '', '', 'kebailey@mtholyoke.edu', '388', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (16, 1, 'American Ballet Theatre Studio Company', 'ACTIVE', 1177681039, 1177681039, 3, 3, 'A', 1177977600, 0, 'NNYA', 'On Saturday, December 9, a 2 pm performance will also be offered.', '', '', '', '', NULL, 'Studio Theater/Kendall', '', '', 'kebailey@mtholyoke.edu', '388', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (17, 1, 'Intro to Swing Dancing', 'ACTIVE', 1177681039, 1177681039, 3, 3, 'T', 1177977600, 0, 'NNYT', '', '', '', '', '', NULL, 'Kendall Sports & Dance Complex, Studio I', '', '', '', '2544', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (18, 1, 'Intro to Swing Dancing', 'ACTIVE', 1177681039, 1177681039, 3, 3, 'A', 1178010000, 1178038800, 'All Day, 9-5', '', '', '', '', '', NULL, 'Kendall Sports & Dance Complex, Studio I', '', '', '', '2544', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (19, 1, 'Intro to Swing Dancing', 'ACTIVE', 1177681040, 1177681040, 3, 3, 'T', 1177977600, 0, 'Timed, 00:00-No end date', '', '', '', '', '', NULL, 'Kendall Sports & Dance Complex, Studio I', '', '', '', '2544', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (20, 1, 'Intro to Swing Dancing', 'ACTIVE', 1177681040, 1177681040, 3, 3, 'A', 1177977600, 1178755200, '1st May - 10th May', '', '', '', '', '', NULL, 'Kendall Sports & Dance Complex, Studio I', '', '', '', '2544', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (21, 1, 'Intro to Swing Dancing', 'ACTIVE', 1177681040, 1177681040, 3, 3, 'A', 1169384400, 0, '', '', '', '', '', '', NULL, 'Kendall Sports & Dance Complex, Studio I', '', '', '', '2544', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (22, 1, 'MHC Community Breakfast', 'ACTIVE', 1177681040, 1177681040, 3, 3, 'A', 1171699200, 0, '', 'President Joanne V. Creighton and the senior staff invite students, faculty, and staff to join them for an informal continental breakfast and good conversation.', '', '', '', '', NULL, 'Blanchard Campus Center', '', '', 'jlytle@mtholyoke.edu', '2464', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (23, 1, 'Showcasing the Real You: Interviewing and Marketing Smarts', 'ACTIVE', 1177681040, 1177681040, 3, 3, 'A', 1173085200, 0, '', '', '', '', '', '', NULL, 'Clapp Laboratory, Hooker Auditorium', '', '', '', '2599', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (24, 1, 'Night of Classical Indian Dance', 'ACTIVE', 1177681040, 1177681040, 3, 3, 'A', 1175452200, 0, '', '', '', '', '', '', NULL, 'Mary Woolley Hall, Chapin Auditorium', '', '', 'achakrab', '4085', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (25, 1, 'Reflexion: The Mount Holyoke College Spring Student Dance Concert', 'ACTIVE', 1177681040, 1177681040, 3, 3, 'A', 1175972400, 0, '', '', '', '', '', '', NULL, 'Kendall Sports and Dance Complex, Studio Theatre', '', '', 'dance-reservations@mtholyoke.edu', '2848', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (26, 1, 'Reflexion: The Mount Holyoke College Spring Student Dance Concert', 'ACTIVE', 1177681040, 1177681040, 3, 3, 'A', 1176058800, 0, '', '', '', '', '', '', NULL, 'Kendall Sports and Dance Complex, Studio Theatre', '', '', 'dance-reservations@mtholyoke.edu', '2848', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (27, 1, 'Reflexion: The Mount Holyoke College Spring Student Dance Concert', 'ACTIVE', 1177681040, 1177681040, 3, 3, 'A', 1176145200, 0, '', '', '', '', '', '', NULL, 'Kendall Sports and Dance Complex, Studio Theatre', '', '', 'dance-reservations@mtholyoke.edu', '2848', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (28, 1, '60th Annual Undergraduate Psychology Research Conference', 'ACTIVE', 1177681040, 1177681040, 3, 3, 'T', 1177315200, 0, '', 'Mount Holyoke?s chapter of Psi Chiwill host its annual Undergraduate Research Conference on SaturdayApril 21, in the Reese Psychology &amp; Education building. Our own Gail Hornsteinwill give the keynote address, ?First-Person Narratives of Madness: TheExpertise of Experience.? Several students from Mount Holyoke and othercolleges in the New England area will also present.', 'http://www.iema.net/', '', '', '', NULL, 'Reese Psychology and Education Building', '', '', 'hmpark@mtholyoke.edu', '4923', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (29, 1, 'The Global & The Intimate: Gender Studies & The Present Crisis of Citizenship', 'ACTIVE', 1177681040, 1177681040, 3, 3, 'T', 1177801200, 0, '', 'The Department of Gender Studies and Women''s Studies Quarterly are hosting this two-day conference.For conference details, go to http://www.mtholyoke.edu/acad/womst/events/conf/', '', '', '', '', NULL, 'Mount Holyoke College', '', '', 'genderstudies@mtholyoke.edu', '', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (30, 1, 'The Global & The Intimate: Gender Studies & The Present Crisis of Citizenship', 'ACTIVE', 1177681040, 1177681040, 3, 3, 'T', 1177887600, 0, '', 'The Department of Gender Studies and Women''s Studies Quarterly are hosting this two-day conference.For conference details, go to http://www.mtholyoke.edu/acad/womst/events/conf/', '', '', '', '', NULL, 'Mount Holyoke College', '', '', 'genderstudies@mtholyoke.edu', '', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (31, 1, 'New England Women''s Leadership Conference', 'ACTIVE', 1177681040, 1177681040, 3, 3, 'T', 1191193200, 0, '', 'This Conference is the premiere event in the Northeast focused on opening opportunities for professional success and leadership for undergraduate women.This is a unique opportunity for undergraduate women to learn from successful women leaders, explore career opportunities in different fields such as finance and science, meet potential mentors, expand networks, and talk to company representatives from the leading global financial services firms.', '', '', '', '', NULL, 'TBD', '', '', '', '', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (32, 1, 'Jhumka Dance Team Tryouts', 'ACTIVE', 1177681050, 1177681050, 3, 3, 'A', 1157983200, 0, '', '', '', '', '', '', NULL, 'Mary Woolley Hall, Chapin Auditorium', '', '', '', '571-232-2092', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (33, 1, 'Gender Free Contra Dance', 'ACTIVE', 1177681050, 1177681050, 3, 3, 'A', 1158690600, 0, '', '', '', '', '', '', NULL, 'Blanchard Campus Center, Great Room and Balcony', '', '', 'mrmoon@mtholyoke.edu', '', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (34, 1, 'SIZZLIN', 'ACTIVE', 1177681050, 1177681050, 3, 3, 'A', 1159822800, 0, '', '', '', '', '', '', NULL, 'Blanchard Campus Center, Great Room and Balcony', '', '', '', '2459', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (35, 1, 'Community Breakfast', 'ACTIVE', 1177681050, 1177681050, 3, 3, 'A', 1160204400, 0, '', 'President Joanne V. Creighton and the senior staff invite students, faculty, and staff to join them for an informal continental breakfast and good conversation.', '', '', '', '', NULL, 'Blanchard Campus Center', '', '', '', '2464', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (36, 1, 'Temptasian', 'ACTIVE', 1177681050, 1177681050, 3, 3, 'A', 1160254800, 0, '', '', '', '', '', '', NULL, 'Blanchard Campus Center, Great Room and Balcony', '', '', 'mhc.jhumka@gmail.com', '240-353-0561', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (37, 1, 'The New England Women''s Conference on Global Finance and Business', 'ACTIVE', 1177681050, 1177681050, 3, 3, 'A', 1160982000, 0, '', 'The New England Women''s Conference on Global Finance and Business presented by the Lyons Network focuses on opening opportunities for professional success and leadership in the field of global fiance and business for undergraduate women. The conference is sponsored by JP Morgan Chase, Goldman Sachs, Credit Suisse, and 85 Broads. Undergraduate women from 30 liberal arts colleges and 20 universities across the Northeast will participate.', '', '', '', '', NULL, 'Gamble Auditorium', '', '', 'registration@thelyonsnetwork.org', '', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (38, 1, 'MHACASA Signature Dance: The Electric Slide', 'ACTIVE', 1177681050, 1177681050, 3, 3, 'A', 1162483200, 0, '', '', '', '', '', '', NULL, 'Blanchard Campus Center, Steps (Facing Skinner Green)', '', '', 'tsmalcol', '8866', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (39, 1, 'The Hartford-Springfield Economic Partnership Third Annual College Career Expo', 'ACTIVE', 1177681050, 1177681050, 3, 3, 'A', 1162645200, 0, '', 'Please check www.collegecareerexpo.com for more information', '', '', '', '', NULL, 'Rentschler Field, East Hartford', '', '', '', '2080', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (40, 1, 'Fusion Fever', 'ACTIVE', 1177681050, 1177681050, 3, 3, 'A', 1163455200, 0, '', '', '', '', '', '', NULL, 'Blanchard Campus Center, Great Room and Balcony', '', '', 'anwar20f@mtholyoke.edu', '240-353-0561', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (41, 1, 'Legacies of Leadership: A Student Conference', 'ACTIVE', 1177681050, 1177681050, 3, 3, 'A', 1164018600, 0, '', 'MHC students are invited to attend a day of engaging workshops and inspiring discussion about personal leadership and success.', '', '', '', '', NULL, 'Willits-Hallowell Center', '', '', 'wcl@mtholyoke.edu', '3071', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (42, 1, 'American Ballet Theatre Studio Company', 'ACTIVE', 1177681050, 1177681050, 3, 3, 'A', 1165780800, 0, '', 'On Saturday, December 9, a 2 pm performance will also be offered.', '', '', '', '', NULL, 'Studio Theater/Kendall', '', '', 'kebailey@mtholyoke.edu', '388', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (43, 1, 'American Ballet Theatre Studio Company', 'ACTIVE', 1177681050, 1177681050, 3, 3, 'A', 1165867200, 0, '', 'On Saturday, December 9, a 2 pm performance will also be offered.', '', '', '', '', NULL, 'Studio Theater/Kendall', '', '', 'kebailey@mtholyoke.edu', '388', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (44, 1, 'Intro to Swing Dancing', 'ACTIVE', 1177681050, 1177681050, 3, 3, 'A', 1168434000, 0, '', '', '', '', '', '', NULL, 'Kendall Sports & Dance Complex, Studio I', '', '', '', '2544', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (45, 1, 'Intro to Swing Dancing', 'ACTIVE', 1177681050, 1177681050, 3, 3, 'A', 1168606800, 0, '', '', '', '', '', '', NULL, 'Kendall Sports & Dance Complex, Studio I', '', '', '', '2544', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (46, 1, 'Intro to Swing Dancing', 'ACTIVE', 1177681050, 1177681050, 3, 3, 'A', 1168779600, 0, '', '', '', '', '', '', NULL, 'Kendall Sports & Dance Complex, Studio I', '', '', '', '2544', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (47, 1, 'Intro to Swing Dancing', 'ACTIVE', 1177681050, 1177681050, 3, 3, 'A', 1169211600, 0, '', '', '', '', '', '', NULL, 'Kendall Sports & Dance Complex, Studio I', '', '', '', '2544', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (48, 1, 'Intro to Swing Dancing', 'ACTIVE', 1177681050, 1177681050, 3, 3, 'A', 1169384400, 0, '', '', '', '', '', '', NULL, 'Kendall Sports & Dance Complex, Studio I', '', '', '', '2544', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (49, 1, 'MHC Community Breakfast', 'ACTIVE', 1177681050, 1177681050, 3, 3, 'A', 1171699200, 0, '', 'President Joanne V. Creighton and the senior staff invite students, faculty, and staff to join them for an informal continental breakfast and good conversation.', '', '', '', '', NULL, 'Blanchard Campus Center', '', '', 'jlytle@mtholyoke.edu', '2464', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (50, 1, 'Showcasing the Real You: Interviewing and Marketing Smarts', 'ACTIVE', 1177681050, 1177681050, 3, 3, 'A', 1173085200, 0, '', '', '', '', '', '', NULL, 'Clapp Laboratory, Hooker Auditorium', '', '', '', '2599', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (51, 1, 'Night of Classical Indian Dance', 'ACTIVE', 1177681050, 1177681050, 3, 3, 'A', 1175452200, 0, '', '', '', '', '', '', NULL, 'Mary Woolley Hall, Chapin Auditorium', '', '', 'achakrab', '4085', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (52, 1, 'Reflexion: The Mount Holyoke College Spring Student Dance Concert', 'ACTIVE', 1177681050, 1177681050, 3, 3, 'A', 1175972400, 0, '', '', '', '', '', '', NULL, 'Kendall Sports and Dance Complex, Studio Theatre', '', '', 'dance-reservations@mtholyoke.edu', '2848', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (53, 1, 'Reflexion: The Mount Holyoke College Spring Student Dance Concert', 'ACTIVE', 1177681050, 1177681050, 3, 3, 'A', 1176058800, 0, '', '', '', '', '', '', NULL, 'Kendall Sports and Dance Complex, Studio Theatre', '', '', 'dance-reservations@mtholyoke.edu', '2848', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (54, 1, 'Reflexion: The Mount Holyoke College Spring Student Dance Concert', 'ACTIVE', 1177681050, 1177681050, 3, 3, 'A', 1176145200, 0, '', '', '', '', '', '', NULL, 'Kendall Sports and Dance Complex, Studio Theatre', '', '', 'dance-reservations@mtholyoke.edu', '2848', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (55, 1, '60th Annual Undergraduate Psychology Research Conference', 'ACTIVE', 1177681050, 1177681050, 3, 3, 'T', 1177315200, 0, '', 'Mount Holyoke?s chapter of Psi Chiwill host its annual Undergraduate Research Conference on SaturdayApril 21, in the Reese Psychology &amp; Education building. Our own Gail Hornsteinwill give the keynote address, ?First-Person Narratives of Madness: TheExpertise of Experience.? Several students from Mount Holyoke and othercolleges in the New England area will also present.', '', '', '', '', NULL, 'Reese Psychology and Education Building', '', '', 'hmpark@mtholyoke.edu', '4923', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (56, 1, 'The Global & The Intimate: Gender Studies & The Present Crisis of Citizenship', 'ACTIVE', 1177681050, 1177681050, 3, 3, 'T', 1177801200, 0, '', 'The Department of Gender Studies and Women''s Studies Quarterly are hosting this two-day conference.For conference details, go to http://www.mtholyoke.edu/acad/womst/events/conf/', '', '', '', '', NULL, 'Mount Holyoke College', '', '', 'genderstudies@mtholyoke.edu', '', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (57, 1, 'The Global & The Intimate: Gender Studies & The Present Crisis of Citizenship', 'ACTIVE', 1177681050, 1177681050, 3, 3, 'T', 1177887600, 0, '', 'The Department of Gender Studies and Women''s Studies Quarterly are hosting this two-day conference.For conference details, go to http://www.mtholyoke.edu/acad/womst/events/conf/', '', '', '', '', NULL, 'Mount Holyoke College', '', '', 'genderstudies@mtholyoke.edu', '', '', '');
INSERT INTO `xar_ievents_events` (`eid`, `calendar_id`, `title`, `status`, `created_time`, `updated_time`, `created_by`, `updated_by`, `all_day`, `start_date`, `end_date`, `summary`, `description`, `url`, `external_source`, `external_ref`, `flags`, `location_venue`, `location_address`, `location_country`, `location_postcode`, `contact_email`, `contact_phone`, `contact_details`, `cost`) VALUES (58, 1, 'New England Women''s Leadership Conference', 'ACTIVE', 1177681050, 1177681050, 3, 3, 'T', 1191193200, 0, '', 'This Conference is the premiere event in the Northeast focused on opening opportunities for professional success and leadership for undergraduate women.This is a unique opportunity for undergraduate women to learn from successful women leaders, explore career opportunities in different fields such as finance and science, meet potential mentors, expand networks, and talk to company representatives from the leading global financial services firms.', '', '', '', '', NULL, 'TBD', '', '', '', '', '', '');
