<?php
function netquery_admin_xaports()
{
    if (!xarSecurityCheck('EditRole')) return;
    if (!xarVarFetch('step', 'int:1:10', $step, '1', XARVAR_NOT_REQUIRED)) return;
    if (!xarVarFetch('phase', 'str:1:100', $phase, 'display', XARVAR_NOT_REQUIRED)) return;
    $data = array();
    $data['step'] = $step;
    $data['phase'] = $phase;
    $stepphase = $step.'-'.$phase;
    switch ($stepphase) {
        case '1-display':
        default:
            $data['body'] = '<br /><br />The first step in building a new ports table is to delete the existing table.';
            $data['body'] .= ' Unless it has been backed up, all of the data contained in that table will be lost.';
            $data['body'] .= '<br /><br />Do you wish to proceed?:';
            $data['body'] .= ' [<a href="'.xarModURL('netquery', 'admin', 'xaports', array('step' => '1', 'phase' => 'update')).'">Yes</a>]';
            $data['body'] .= ' [<a href="'.xarModURL('netquery', 'admin', 'config').'">No</a>]<br /><br />';
            break;
        case '1-update':
            $dbconn =& xarDBGetConn();
            $xartable =& xarDBGetTables();
            $PortsTable = $xartable['netquery_ports'];
            $query = "DROP TABLE IF EXISTS ".$PortsTable;
            $result =& $dbconn->Execute($query);
            $query = "CREATE TABLE ".$PortsTable." (
              port_id mediumint(9) NOT NULL auto_increment,
              port  mediumint(9) NOT NULL default '0',
              protocol varchar(3) NOT NULL default '',
              service varchar(35) NOT NULL default '',
              comment varchar(50) NOT NULL default '',
              flag tinyint(4) NOT NULL default '0',
              PRIMARY KEY (port_id)
            ) ;";
            $result =& $dbconn->Execute($query);
            $query = "INSERT INTO ".$PortsTable." VALUES
(0, 1, 'tcp', 'tcpmux', 'TCP Port Service Multiplexer [rfc-1078]', 0),
(0, 1, 'udp', 'SocketsdesTroie', 'Sockets des Troie', 1),
(0, 1, 'udp', 'tcpmux', 'TCP Port Service Multiplexer', 0),
(0, 2, 'tcp', 'compressnet', 'Management Utility', 0),
(0, 2, 'tcp', 'Death', 'Death', 1),
(0, 2, 'udp', 'compressnet', 'Management Utility', 0),
(0, 3, 'tcp', 'compressnet', 'Compression Process', 0),
(0, 3, 'udp', 'compressnet', 'Compression Process', 0),
(0, 4, 'tcp', 'Unassigned', 'Unassigned', 0),
(0, 4, 'udp', 'Unassigned', 'Unassigned', 0),
(0, 5, 'tcp', 'rje', 'Remote Job Entry', 0),
(0, 5, 'udp', 'rje', 'Remote Job Entry', 0),
(0, 6, 'tcp', 'Unassigned', 'Unassigned', 0),
(0, 6, 'udp', 'Unassigned', 'Unassigned', 0),
(0, 7, 'tcp', 'echo', 'Echo', 0),
(0, 7, 'udp', 'echo', 'Echo', 0),
(0, 8, 'tcp', 'Unassigned', 'Unassigned', 0),
(0, 8, 'udp', 'Unassigned', 'Unassigned', 0),
(0, 9, 'tcp', 'discard', 'Discard', 0),
(0, 9, 'udp', 'discard', 'Discard', 0),
(0, 10, 'tcp', 'Unassigned', 'Unassigned', 0),
(0, 10, 'udp', 'Unassigned', 'Unassigned', 0),
(0, 11, 'tcp', 'systat', 'Active Users', 0),
(0, 11, 'udp', 'systat', 'Active Users', 0),
(0, 12, 'tcp', 'Unassigned', 'Unassigned', 0),
(0, 12, 'udp', 'Unassigned', 'Unassigned', 0),
(0, 13, 'tcp', 'daytime', 'Daytime', 0),
(0, 13, 'udp', 'daytime', 'Daytime', 0),
(0, 14, 'tcp', 'Unassigned', 'Unassigned', 0),
(0, 14, 'udp', 'Unassigned', 'Unassigned', 0),
(0, 15, 'tcp', 'netstat', 'Netstat', 0),
(0, 15, 'tcp', 'B2', 'B2', 1),
(0, 15, 'tcp', 'Unassigned', 'Unassigned [was netstat]', 0),
(0, 15, 'udp', 'Unassigned', 'Unassigned', 0),
(0, 16, 'tcp', 'Unassigned', 'Unassigned', 0),
(0, 16, 'udp', 'Unassigned', 'Unassigned', 0),
(0, 17, 'tcp', 'qotd', 'Quote of the Day', 0),
(0, 17, 'udp', 'qotd', 'Quote of the Day', 0),
(0, 18, 'tcp', 'msp', 'Message Send Protocol', 0),
(0, 18, 'udp', 'msp', 'Message Send Protocol', 0),
(0, 19, 'tcp', 'chargen', 'Character Generator', 0),
(0, 19, 'udp', 'chargen', 'Character Generator', 0),
(0, 20, 'tcp', 'ftp-data', 'File Transfer [Default Data]', 0),
(0, 20, 'udp', 'ftp-data', 'File Transfer [Default Data]', 0),
(0, 20, 'tcp', 'SennaSpyFTPserver', 'Senna Spy FTP server', 1),
(0, 21, 'tcp', 'ftp', 'File Transfer [Control]', 0),
(0, 21, 'udp', 'ftp', 'File Transfer [Control]', 0),
(0, 21, 'tcp', 'BackConstruction', 'Back Construction', 1),
(0, 21, 'tcp', 'BladeRunner', 'BladeRunner', 1),
(0, 21, 'tcp', 'CattivikFTPServer', 'Cattivik FTP Server', 1),
(0, 21, 'tcp', 'CCInvader', 'CC Invader', 1),
(0, 21, 'tcp', 'DarkFTP', 'Dark FTP', 1),
(0, 21, 'tcp', 'DolyTrojan', 'Doly Trojan', 1),
(0, 21, 'tcp', 'Fore', 'Fore', 1),
(0, 21, 'tcp', 'FreddyK', 'FreddyK', 1),
(0, 21, 'tcp', 'InvisibleFTP', 'Invisible FTP', 1),
(0, 21, 'tcp', 'Juggernaut42', 'Juggernaut 42', 1),
(0, 21, 'tcp', 'Larva', 'Larva', 1),
(0, 21, 'tcp', 'MotIvFTP', 'MotIv FTP', 1),
(0, 21, 'tcp', 'NetAdministrator', 'Net Administrator', 1),
(0, 21, 'tcp', 'Ramen', 'Ramen', 1),
(0, 21, 'tcp', 'RTB666', 'RTB 666', 1),
(0, 21, 'tcp', 'SennaSpyFTPserver', 'Senna Spy FTP server', 1),
(0, 21, 'tcp', 'Traitor21', 'Traitor 21', 1),
(0, 21, 'tcp', 'TheFlu', 'The Flu', 1),
(0, 21, 'tcp', 'WebEx', 'WebEx', 1),
(0, 21, 'tcp', 'WinCrash', 'WinCrash', 1),
(0, 21, 'tcp', 'AudioGalaxy', 'AudioGalaxy file sharing app', 0),
(0, 22, 'tcp', 'Adoresshd', 'Adore sshd', 1),
(0, 22, 'tcp', 'Shaft', 'Shaft', 1),
(0, 22, 'tcp', 'ssh', 'SSH Remote Login Protocol', 0),
(0, 22, 'udp', 'pcanywhere', 'PCAnywhere (deprecated)', 0),
(0, 22, 'udp', 'ssh', 'SSH Remote Login Protocol', 0),
(0, 23, 'tcp', 'telnet', 'Telnet', 0),
(0, 23, 'udp', 'telnet', 'Telnet', 0),
(0, 23, 'tcp', 'ADMworm', 'ADM worm', 1),
(0, 23, 'tcp', 'FireHacKer', 'Fire HacKer', 1),
(0, 23, 'tcp', 'MyVeryOwntrojan', 'My Very Own trojan', 1),
(0, 23, 'tcp', 'RTB666', 'RTB 666', 1),
(0, 23, 'tcp', 'TelnetPro', 'Telnet Pro', 1),
(0, 23, 'tcp', 'TinyTelnetServer', 'Tiny Telnet Server - TTS', 1),
(0, 23, 'tcp', 'TruvaAtl', 'Truva Atl', 1),
(0, 24, 'tcp', 'BO2KControlPort', 'Back Orifice 2000 (BO2K) Control Port', 1),
(0, 24, 'tcp', 'priv-mail', 'any private mail system', 0),
(0, 24, 'udp', 'priv-mail', 'any private mail system', 0),
(0, 25, 'tcp', 'smtp', 'Simple Mail Transfer', 0),
(0, 25, 'udp', 'smtp', 'Simple Mail Transfer', 0),
(0, 25, 'tcp', 'Ajan', 'Ajan', 1),
(0, 25, 'tcp', 'Antigen', 'Antigen', 1),
(0, 25, 'tcp', 'Barok', 'Barok', 1),
(0, 25, 'tcp', 'BSE', 'BSE', 1),
(0, 25, 'tcp', 'EmailPasswordSender', 'Email Password Sender - EPS', 1),
(0, 25, 'tcp', 'EPSII', 'EPS II', 1),
(0, 25, 'tcp', 'Gip', 'Gip', 1),
(0, 25, 'tcp', 'Gris', 'Gris', 1),
(0, 25, 'tcp', 'Happy99', 'Happy99', 1),
(0, 25, 'tcp', 'Hpteammail', 'Hpteam mail', 1),
(0, 25, 'tcp', 'Hybris', 'Hybris', 1),
(0, 25, 'tcp', 'Iloveyou', 'I love you', 1),
(0, 25, 'tcp', 'Kuang2', 'Kuang2', 1),
(0, 25, 'tcp', 'MagicHorse', 'Magic Horse', 1),
(0, 25, 'tcp', 'MBTMailBombingTrojan', 'MBT (Mail Bombing Trojan)', 1),
(0, 25, 'tcp', 'MBT', 'MBT (Mail Bombing Trojan)', 1),
(0, 25, 'tcp', 'MoscowEmailtrojan', 'Moscow Email trojan', 1),
(0, 25, 'tcp', 'Naebi', 'Naebi', 1),
(0, 25, 'tcp', 'NewAptworm', 'NewApt worm', 1),
(0, 25, 'tcp', 'ProMailtrojan', 'ProMail trojan', 1),
(0, 25, 'tcp', 'Shtirlitz', 'Shtirlitz', 1),
(0, 25, 'tcp', 'Stealth', 'Stealth', 1),
(0, 25, 'tcp', 'Stukach', 'Stukach', 1),
(0, 25, 'tcp', 'Tapiras', 'Tapiras', 1),
(0, 25, 'tcp', 'Terminator', 'Terminator', 1),
(0, 25, 'tcp', 'WinPC', 'WinPC', 1),
(0, 25, 'tcp', 'WinSpy', 'WinSpy', 1),
(0, 26, 'tcp', 'altavista-fw97', 'AltaVista Firewall97', 0),
(0, 26, 'tcp', 'Unassigned', 'Unassigned', 0),
(0, 26, 'udp', 'Unassigned', 'Unassigned', 0),
(0, 27, 'tcp', 'altavista-fw97', 'AltaVista Firewall97', 0),
(0, 27, 'tcp', 'nsw-fe', 'NSW User System FE', 0),
(0, 27, 'udp', 'nsw-fe', 'NSW User System FE', 0),
(0, 28, 'tcp', 'altavista-fw97', 'AltaVista Firewall97', 0),
(0, 28, 'tcp', 'Unassigned', 'Unassigned', 0),
(0, 28, 'udp', 'Unassigned', 'Unassigned', 0),
(0, 29, 'tcp', 'altavista-fw97', 'AltaVista Firewall97', 0),
(0, 29, 'tcp', 'msg-icp', 'MSG ICP', 0),
(0, 29, 'udp', 'msg-icp', 'MSG ICP', 0),
(0, 30, 'tcp', 'Agent40421', 'Agent 40421', 1),
(0, 30, 'tcp', 'Unassigned', 'Unassigned', 0),
(0, 30, 'udp', 'Unassigned', 'Unassigned', 0),
(0, 31, 'tcp', 'msg-auth', 'MSG Authentication', 0),
(0, 31, 'udp', 'msg-auth', 'MSG Authentication', 0),
(0, 31, 'tcp', 'Agent31', 'Agent 31', 1),
(0, 31, 'tcp', 'Agent31', 'Agent 31', 1),
(0, 31, 'tcp', 'HackersParadise', 'Hackers Paradise', 1),
(0, 31, 'tcp', 'MastersParadise', 'Masters Paradise', 1),
(0, 32, 'tcp', 'Unassigned', 'Unassigned', 0),
(0, 32, 'udp', 'Unassigned', 'Unassigned', 0),
(0, 33, 'tcp', 'dsp', 'Display Support Protocol', 0),
(0, 33, 'udp', 'dsp', 'Display Support Protocol', 0),
(0, 34, 'tcp', 'Unassigned', 'Unassigned', 0),
(0, 34, 'udp', 'Unassigned', 'Unassigned', 0),
(0, 35, 'tcp', 'priv-print', 'any private printer server', 0),
(0, 35, 'udp', 'priv-print', 'any private printer server', 0),
(0, 36, 'tcp', 'Unassigned', 'Unassigned', 0),
(0, 36, 'udp', 'Unassigned', 'Unassigned', 0),
(0, 37, 'tcp', 'time', 'Time', 0),
(0, 37, 'udp', 'time', 'Time', 0),
(0, 38, 'tcp', 'rap', 'Route Access Protocol', 0),
(0, 38, 'udp', 'rap', 'Route Access Protocol', 0),
(0, 39, 'tcp', 'rlp', 'Resource Location Protocol', 0),
(0, 39, 'udp', 'rlp', 'Resource Location Protocol', 0),
(0, 39, 'tcp', 'SubSARI', 'SubSARI', 1),
(0, 40, 'tcp', 'Unassigned', 'Unassigned', 0),
(0, 40, 'udp', 'Unassigned', 'Unassigned', 0),
(0, 41, 'tcp', 'graphics', 'Graphics', 0),
(0, 41, 'udp', 'graphics', 'Graphics', 0),
(0, 41, 'tcp', 'DeepThroat', 'DeepThroat', 1),
(0, 41, 'tcp', 'DeepThroat', 'Deep Throat', 1),
(0, 41, 'tcp', 'Foreplay', 'Foreplay', 1),
(0, 42, 'tcp', 'name', 'Host Name Server', 0),
(0, 42, 'udp', 'name', 'Host Name Server', 0),
(0, 43, 'tcp', 'whois', 'nicname', 0),
(0, 43, 'udp', 'whois', 'nicname', 0),
(0, 44, 'tcp', 'mpm-flags', 'MPM FLAGS Protocol', 0),
(0, 44, 'udp', 'mpm-flags', 'MPM FLAGS Protocol', 0),
(0, 44, 'tcp', 'Arctic', 'Arctic', 1),
(0, 45, 'tcp', 'mpm', 'Message Processing Module [recv]', 0),
(0, 45, 'udp', 'mpm', 'Message Processing Module [recv]', 0),
(0, 46, 'tcp', 'mpm-snd', 'MPM [default send]', 0),
(0, 46, 'udp', 'mpm-snd', 'MPM [default send]', 0),
(0, 47, 'tcp', 'ni-ftp', 'NI FTP', 0),
(0, 47, 'udp', 'ni-ftp', 'NI FTP', 0),
(0, 48, 'tcp', 'auditd', 'Digital Audit Daemon', 0),
(0, 48, 'udp', 'auditd', 'Digital Audit Daemon', 0),
(0, 48, 'tcp', 'DRAT', 'DRAT', 1),
(0, 48, 'tcp', 'DRAT', 'DRAT', 1),
(0, 49, 'tcp', 'tacacs', 'Login Host Protocol (TACACS)', 0),
(0, 49, 'udp', 'tacacs', 'Login Host Protocol (TACACS)', 0),
(0, 50, 'tcp', 're-mail-ck', 'Remote Mail Checking Protocol', 0),
(0, 50, 'udp', 're-mail-ck', 'Remote Mail Checking Protocol', 0),
(0, 50, 'tcp', 'DRAT', 'DRAT', 1),
(0, 50, 'tcp', 'DRAT', 'DRAT', 1),
(0, 51, 'tcp', 'la-maint', 'IMP Logical Address Maintenance', 0),
(0, 51, 'udp', 'la-maint', 'IMP Logical Address Maintenance', 0),
(0, 52, 'tcp', 'xns-time', 'XNS Time Protocol', 0),
(0, 52, 'udp', 'xns-time', 'XNS Time Protocol', 0),
(0, 53, 'tcp', 'domain', 'Domain Name Server', 0),
(0, 53, 'udp', 'domain', 'Domain Name Server', 0),
(0, 53, 'tcp', 'ADMworm', 'ADM worm', 1),
(0, 53, 'tcp', 'Lion', 'Lion', 1),
(0, 54, 'tcp', 'xns-ch', 'XNS Clearinghouse', 0),
(0, 54, 'udp', 'xns-ch', 'XNS Clearinghouse', 0),
(0, 55, 'tcp', 'isi-gl', 'ISI Graphics Language', 0),
(0, 55, 'udp', 'isi-gl', 'ISI Graphics Language', 0),
(0, 56, 'tcp', 'xns-auth', 'XNS Authentication', 0),
(0, 56, 'udp', 'xns-auth', 'XNS Authentication', 0),
(0, 57, 'tcp', 'priv-term', 'any private terminal access', 0),
(0, 57, 'udp', 'priv-term', 'any private terminal access', 0),
(0, 57, 'tcp', 'mtp', 'Mail Transfer Protocol', 0),
(0, 58, 'tcp', 'xns-mail', 'XNS Mail', 0),
(0, 58, 'udp', 'xns-mail', 'XNS Mail', 0),
(0, 58, 'tcp', 'DMSetup', 'DMSetup', 1),
(0, 59, 'tcp', 'priv-file', 'any private file service', 0),
(0, 59, 'udp', 'priv-file', 'any private file service', 0),
(0, 59, 'tcp', 'DMSetup', 'DMSetup', 1),
(0, 59, 'tcp', 'DMSetup', 'DMSetup', 1),
(0, 61, 'tcp', 'ni-mail', 'NI MAIL', 0),
(0, 61, 'udp', 'ni-mail', 'NI MAIL', 0),
(0, 62, 'tcp', 'acas', 'ACA Services', 0),
(0, 62, 'udp', 'acas', 'ACA Services', 0),
(0, 63, 'tcp', 'whois++', 'whois++', 0),
(0, 63, 'udp', 'whois++', 'whois++', 0),
(0, 63, 'tcp', 'via-ftp', 'VIA Systems - FTP & whois++', 0),
(0, 63, 'udp', 'via-ftp', 'VIA Systems - FTP & whois++', 0),
(0, 64, 'tcp', 'covia', 'Communications Integrator (CI)', 0),
(0, 64, 'udp', 'covia', 'Communications Integrator (CI)', 0),
(0, 65, 'tcp', 'tacacs-ds', 'TACACS-Database Service', 0),
(0, 65, 'udp', 'tacacs-ds', 'TACACS-Database Service', 0),
(0, 66, 'tcp', 'sql*net', 'Oracle SQL*NET', 0),
(0, 66, 'udp', 'sql*net', 'Oracle SQL*NET', 0),
(0, 67, 'tcp', 'bootps', 'Bootstrap Protocol Server', 0),
(0, 67, 'udp', 'bootps', 'Bootstrap Protocol Server', 0),
(0, 68, 'tcp', 'bootpc', 'Bootstrap Protocol Client', 0),
(0, 68, 'udp', 'bootpc', 'Bootstrap Protocol Client', 0),
(0, 69, 'tcp', 'tftp', 'Trivial File Transfer', 0),
(0, 69, 'udp', 'tftp', 'Trivial File Transfer', 0),
(0, 69, 'tcp', 'BackGate', 'BackGate', 1),
(0, 70, 'tcp', 'gopher', 'Gopher', 0),
(0, 70, 'udp', 'gopher', 'Gopher', 0),
(0, 71, 'tcp', 'netrjs-1', 'Remote Job Service', 0),
(0, 71, 'udp', 'netrjs-1', 'Remote Job Service', 0),
(0, 72, 'tcp', 'netrjs-2', 'Remote Job Service', 0),
(0, 72, 'udp', 'netrjs-2', 'Remote Job Service', 0),
(0, 73, 'tcp', 'netrjs-3', 'Remote Job Service', 0),
(0, 73, 'udp', 'netrjs-3', 'Remote Job Service', 0),
(0, 74, 'tcp', 'netrjs-4', 'Remote Job Service', 0),
(0, 74, 'udp', 'netrjs-4', 'Remote Job Service', 0),
(0, 75, 'tcp', 'priv-dial', 'any private dial out service', 0),
(0, 75, 'udp', 'priv-dial', 'any private dial out service', 0),
(0, 76, 'tcp', 'deos', 'Distributed External Object Store', 0),
(0, 76, 'udp', 'deos', 'Distributed External Object Store', 0),
(0, 77, 'tcp', 'priv-rje', 'any private RJE service  netrjs', 0),
(0, 77, 'udp', 'priv-rje', 'any private RJE service  netjrs', 0),
(0, 78, 'tcp', 'vettcp', 'vettcp', 0),
(0, 78, 'udp', 'vettcp', 'vettcp', 0),
(0, 79, 'tcp', 'finger', 'Finger', 0),
(0, 79, 'udp', 'finger', 'Finger', 0),
(0, 79, 'tcp', 'BO2KDataPort', 'Back Orifice 2000 (BO2K) Data Port', 1),
(0, 79, 'tcp', 'CDK', 'CDK', 1),
(0, 79, 'tcp', 'Firehotcker', 'Firehotcker', 1),
(0, 80, 'tcp', 'http', 'World Wide Web HTTP', 0),
(0, 80, 'udp', 'http', 'World Wide Web HTTP', 0),
(0, 80, 'tcp', '711trojan', '711 trojan (Seven Eleven)', 1),
(0, 80, 'tcp', 'AckCmd', 'AckCmd', 1),
(0, 80, 'tcp', 'AckCmd', 'AckCmd', 1),
(0, 80, 'tcp', 'BackEnd', 'Back End', 1),
(0, 80, 'tcp', 'BO2000Plug-Ins', 'Back Orifice 2000 Plug-Ins', 1),
(0, 80, 'tcp', 'Cafeini', 'Cafeini', 1),
(0, 80, 'tcp', 'CGIBackdoor', 'CGI Backdoor', 2),
(0, 80, 'tcp', 'Executor', 'Executor', 1),
(0, 80, 'tcp', 'GodMessage4Creator', 'God Message 4 Creator', 1),
(0, 80, 'tcp', 'GodMessage', 'God Message', 1),
(0, 80, 'tcp', 'Hooker', 'Hooker', 1),
(0, 80, 'tcp', 'IISworm', 'IISworm', 1),
(0, 80, 'tcp', 'MTX', 'MTX', 1),
(0, 80, 'tcp', 'NCX', 'NCX', 1),
(0, 80, 'tcp', 'Noob', 'Noob', 1),
(0, 80, 'tcp', 'Ramen', 'Ramen', 1),
(0, 80, 'tcp', 'ReverseWWWTunnel', 'Reverse WWW Tunnel', 2),
(0, 80, 'tcp', 'RingZero', 'RingZero', 1),
(0, 80, 'tcp', 'RTB666', 'RTB 666', 1),
(0, 80, 'tcp', 'Seeker', 'Seeker', 1),
(0, 80, 'tcp', 'WANRemote', 'WAN Remote', 1),
(0, 80, 'tcp', 'WebDownloader', 'WebDownloader', 1),
(0, 80, 'tcp', 'WebServerCT', 'Web Server CT', 1),
(0, 81, 'tcp', 'hosts2-ns', 'HOSTS2 Name Server', 0),
(0, 81, 'udp', 'hosts2-ns', 'HOSTS2 Name Server', 0),
(0, 81, 'tcp', 'RemoConChubo', 'RemoConChubo', 1),
(0, 81, 'tcp', 'RemoConChubo', 'RemoConChubo', 1),
(0, 82, 'tcp', 'xfer', 'XFER Utility', 0),
(0, 82, 'udp', 'xfer', 'XFER Utility', 0),
(0, 83, 'tcp', 'mit-ml-dev', 'MIT ML Device', 0),
(0, 83, 'udp', 'mit-ml-dev', 'MIT ML Device', 0),
(0, 84, 'tcp', 'ctf', 'Common Trace Facility', 0),
(0, 84, 'udp', 'ctf', 'Common Trace Facility', 0),
(0, 85, 'tcp', 'mit-ml-dev', 'MIT ML Device', 0),
(0, 85, 'udp', 'mit-ml-dev', 'MIT ML Device', 0),
(0, 86, 'tcp', 'mfcobol', 'Micro Focus Cobol', 0),
(0, 86, 'udp', 'mfcobol', 'Micro Focus Cobol', 0),
(0, 87, 'tcp', 'priv-term-l', 'any private terminal link  ttylink', 0),
(0, 88, 'tcp', 'kerberos', 'Kerberos', 0),
(0, 88, 'udp', 'kerberos', 'Kerberos', 0),
(0, 89, 'tcp', 'su-mit-tg', 'SU MIT Telnet Gateway', 0),
(0, 89, 'udp', 'su-mit-tg', 'SU MIT Telnet Gateway', 0),
(0, 90, 'tcp', 'dnsix', 'DNSIX Securit Attribute Token Map', 0),
(0, 90, 'udp', 'dnsix', 'DNSIX Securit Attribute Token Map', 0),
(0, 91, 'tcp', 'mit-dov', 'MIT Dover Spooler', 0),
(0, 91, 'udp', 'mit-dov', 'MIT Dover Spooler', 0),
(0, 92, 'tcp', 'npp', 'Network Printing Protocol', 0),
(0, 92, 'udp', 'npp', 'Network Printing Protocol', 0),
(0, 93, 'tcp', 'dcp', 'Device Control Protocol', 0),
(0, 93, 'udp', 'dcp', 'Device Control Protocol', 0),
(0, 94, 'tcp', 'objcall', 'Tivoli Object Dispatcher', 0),
(0, 94, 'udp', 'objcall', 'Tivoli Object Dispatcher', 0),
(0, 95, 'tcp', 'supdup', 'BSD supdupd(8)', 0),
(0, 95, 'udp', 'supdup', 'BSD supdupd(8)', 0),
(0, 96, 'tcp', 'dixie', 'DIXIE Protocol Specification', 0),
(0, 96, 'udp', 'dixie', 'DIXIE Protocol Specification', 0),
(0, 97, 'tcp', 'swift-rvf', 'Swift Remote Virtural File Protocol', 0),
(0, 97, 'udp', 'swift-rvf', 'Swift Remote Virtural File Protocol', 0),
(0, 98, 'tcp', 'linuxconf', 'linuxconf', 0),
(0, 98, 'tcp', 'tacnews', 'TAC News', 0),
(0, 98, 'udp', 'tacnews', 'TAC News', 0),
(0, 99, 'tcp', 'metagram', 'Metagram Relay', 0),
(0, 99, 'udp', 'metagram', 'Metagram Relay', 0),
(0, 99, 'tcp', 'HiddenPort', 'Hidden Port', 1),
(0, 99, 'tcp', 'Hidden', 'Hidden', 1),
(0, 99, 'tcp', 'Mandragore', 'Mandragore', 1),
(0, 99, 'tcp', 'NCX', 'NCX', 1),
(0, 100, 'tcp', 'newacct', '[unauthorized use]', 0),
(0, 101, 'tcp', 'hostname', 'NIC Host Name Server', 0),
(0, 101, 'udp', 'hostname', 'NIC Host Name Server', 0),
(0, 102, 'tcp', 'iso-tsap', 'ISO Transport Service Access Point', 0),
(0, 102, 'udp', 'iso-tsap', 'ISO Transport Service Access Point', 0),
(0, 103, 'tcp', 'gppitnp', 'Genesis Point-to-Point Trans Net', 0),
(0, 103, 'udp', 'gppitnp', 'Genesis Point-to-Point Trans Net', 0),
(0, 104, 'tcp', 'acr-nema', 'ACR-NEMA Digital Imag & Comm 300', 0),
(0, 104, 'udp', 'acr-nema', 'ACR-NEMA Digital Imag & Comm 300', 0),
(0, 105, 'tcp', 'csnet-ns', 'Mailbox Name Nameserver', 0),
(0, 105, 'udp', 'csnet-ns', 'Mailbox Name Nameserver', 0),
(0, 105, 'tcp', 'cso', 'CCSO name server protocol', 0),
(0, 105, 'udp', 'cso', 'CCSO name server protocol', 0),
(0, 106, 'tcp', '3com-tsmux', '3COM-TSMUX', 0),
(0, 106, 'udp', '3com-tsmux', '3COM-TSMUX', 0),
(0, 106, 'tcp', 'pop3pw', 'Eudora compatible PW changer', 0),
(0, 107, 'tcp', 'rtelnet', 'Remote Telnet', 0),
(0, 107, 'udp', 'rtelnet', 'Remote Telnet Service', 0),
(0, 108, 'tcp', 'snagas', 'SNA Gateway Access Server', 0),
(0, 108, 'udp', 'snagas', 'SNA Gateway Access Server', 0),
(0, 109, 'tcp', 'pop2', 'PostOffice V2', 0),
(0, 109, 'udp', 'pop2', 'PostOffice V2', 0),
(0, 110, 'tcp', 'pop3', 'PostOffice V3', 0),
(0, 110, 'udp', 'pop3', 'PostOffice V3', 0),
(0, 110, 'tcp', 'ProMailtrojan', 'ProMail trojan', 1),
(0, 110, 'tcp', 'ProMailtrojan', 'ProMail trojan', 1),
(0, 111, 'tcp', 'sunrpc', 'portmapper  rpcbind', 0),
(0, 111, 'udp', 'sunrpc', 'portmapper  rpcbind', 0),
(0, 112, 'tcp', 'mcidas', 'McIDAS Data Transmission Protocol', 0),
(0, 112, 'udp', 'mcidas', 'McIDAS Data Transmission Protocol', 0),
(0, 113, 'tcp', 'auth', 'ident Authentication Service', 0),
(0, 113, 'udp', 'auth', 'ident Authentication Service', 0),
(0, 113, 'tcp', 'InvisibleIdentdDaemon', 'Invisible Identd Daemon', 1),
(0, 113, 'tcp', 'InvisibleIdentdDeamon', 'Invisible Identd Deamon', 1),
(0, 113, 'tcp', 'Kazimas', 'Kazimas', 1),
(0, 114, 'tcp', 'audionews', 'Audio News Multicast', 0),
(0, 114, 'udp', 'audionews', 'Audio News Multicast', 0),
(0, 115, 'tcp', 'sftp', 'Simple File Transfer Protocol', 0),
(0, 115, 'udp', 'sftp', 'Simple File Transfer Protocol', 0),
(0, 116, 'tcp', 'ansanotify', 'ANSA REX Notify', 0),
(0, 116, 'udp', 'ansanotify', 'ANSA REX Notify', 0),
(0, 117, 'tcp', 'uucp-path', 'UUCP Path Service', 0),
(0, 117, 'udp', 'uucp-path', 'UUCP Path Service', 0),
(0, 118, 'tcp', 'sqlserv', 'SQL Services', 0),
(0, 118, 'udp', 'sqlserv', 'SQL Services', 0),
(0, 119, 'tcp', 'nntp', 'Network News Transfer Protocol', 0),
(0, 119, 'udp', 'nntp', 'Network News Transfer Protocol', 0),
(0, 119, 'tcp', 'Happy99', 'Happy99 (aka Ska trojan)', 1),
(0, 120, 'tcp', 'cfdptkt', 'CFDPTKT', 0),
(0, 120, 'udp', 'cfdptkt', 'CFDPTKT', 0),
(0, 121, 'tcp', 'erpc', 'Encore Expedited Remote ProCall', 0),
(0, 121, 'udp', 'erpc', 'Encore Expedited Remote ProCall', 0),
(0, 121, 'tcp', 'AttackBot', 'Attack Bot', 1),
(0, 121, 'tcp', 'GodMessage', 'God Message', 1),
(0, 121, 'tcp', 'JammerKillah', 'JammerKillah', 1),
(0, 121, 'tcp', 'JammerKillah', 'Jammer Killah', 1),
(0, 122, 'tcp', 'smakynet', 'SMAKYNET', 0),
(0, 122, 'udp', 'smakynet', 'SMAKYNET', 0),
(0, 123, 'tcp', 'NetController', 'Net Controller', 1),
(0, 123, 'tcp', 'NetController', 'Net Controller', 1),
(0, 123, 'tcp', 'ntp', 'Network Time Protocol', 0),
(0, 123, 'udp', 'ntp', 'Network Time Protocol', 0),
(0, 124, 'tcp', 'ansatrader', 'ANSA REX Trader', 0),
(0, 124, 'udp', 'ansatrader', 'ANSA REX Trader', 0),
(0, 125, 'tcp', 'locus-map', 'Locus PC-Interface Net Map Ser', 0),
(0, 125, 'udp', 'locus-map', 'Locus PC-Interface Net Map Ser', 0),
(0, 126, 'tcp', 'nxedit', 'NXEdit', 0),
(0, 126, 'udp', 'nxedit', 'NXEdit', 0),
(0, 126, 'tcp', 'unitary', 'Unisys Unitary Login', 0),
(0, 126, 'udp', 'unitary', 'Unisys Unitary Login', 0),
(0, 127, 'tcp', 'locus-con', 'Locus PC-Interface Conn Server', 0),
(0, 127, 'udp', 'locus-con', 'Locus PC-Interface Conn Server', 0),
(0, 128, 'tcp', 'gss-xlicen', 'GSS X License Verification', 0),
(0, 128, 'udp', 'gss-xlicen', 'GSS X License Verification', 0),
(0, 129, 'tcp', 'pwdgen', 'Password Generator Protocol', 0),
(0, 129, 'udp', 'pwdgen', 'Password Generator Protocol', 0),
(0, 130, 'tcp', 'cisco-fna', 'cisco FNATIVE', 0),
(0, 130, 'udp', 'cisco-fna', 'cisco FNATIVE', 0),
(0, 131, 'tcp', 'cisco-tna', 'cisco TNATIVE', 0),
(0, 131, 'udp', 'cisco-tna', 'cisco TNATIVE', 0),
(0, 132, 'tcp', 'cisco-sys', 'cisco SYSMAINT', 0),
(0, 132, 'udp', 'cisco-sys', 'cisco SYSMAINT', 0),
(0, 133, 'tcp', 'statsrv', 'Statistics Service', 0),
(0, 133, 'udp', 'statsrv', 'Statistics Service', 0),
(0, 133, 'tcp', 'Farnaz', 'Farnaz', 1),
(0, 134, 'tcp', 'ingres-net', 'INGRES-NET Service', 0),
(0, 134, 'udp', 'ingres-net', 'INGRES-NET Service', 0),
(0, 135, 'tcp', 'epmap', 'DCE endpoint resolution', 0),
(0, 135, 'udp', 'epmap', 'DCE endpoint resolution', 0),
(0, 135, 'tcp', 'loc-srv', 'NCS Location Service', 0),
(0, 135, 'udp', 'loc-srv', 'NCS Location Service', 0),
(0, 136, 'tcp', 'profile', 'PROFILE Naming System', 0),
(0, 136, 'udp', 'profile', 'PROFILE Naming System', 0),
(0, 137, 'tcp', 'netbios-ns', 'NETBIOS Name Service', 0),
(0, 137, 'udp', 'netbios-ns', 'NETBIOS Name Service', 0),
(0, 137, 'tcp', 'Chode', 'Chode', 1),
(0, 137, 'tcp', 'Qaz', 'Qaz', 1),
(0, 137, 'udp', 'Msinit', 'Msinit', 1),
(0, 138, 'tcp', 'netbios-dgm', 'NETBIOS Datagram Service', 0),
(0, 138, 'udp', 'netbios-dgm', 'NETBIOS Datagram Service', 0),
(0, 138, 'tcp', 'Chode', 'Chode', 1),
(0, 139, 'tcp', 'netbios-ssn', 'NETBIOS Session Service', 0),
(0, 139, 'udp', 'netbios-ssn', 'NETBIOS Session Service', 0),
(0, 139, 'tcp', 'Chode', 'Chode', 1),
(0, 139, 'tcp', 'GodMessageworm', 'God Message worm', 1),
(0, 139, 'tcp', 'Msinit', 'Msinit', 1),
(0, 139, 'tcp', 'Netlog', 'Netlog', 1),
(0, 139, 'tcp', 'Network', 'Network', 1),
(0, 139, 'tcp', 'Qaz', 'Qaz', 1),
(0, 139, 'tcp', 'Sadmind', 'Sadmind', 1),
(0, 139, 'tcp', 'SMBRelay', 'SMB Relay', 1),
(0, 140, 'tcp', 'emfis-data', 'EMFIS Data Service', 0),
(0, 140, 'udp', 'emfis-data', 'EMFIS Data Service', 0),
(0, 141, 'tcp', 'emfis-cntl', 'EMFIS Control Service', 0),
(0, 141, 'udp', 'emfis-cntl', 'EMFIS Control Service', 0),
(0, 142, 'tcp', 'bl-idm', 'Britton-Lee IDM', 0),
(0, 142, 'udp', 'bl-idm', 'Britton-Lee IDM', 0),
(0, 142, 'tcp', 'NetTaxi', 'NetTaxi', 1),
(0, 143, 'tcp', 'imap', 'Internet Message Access Protocol', 0),
(0, 143, 'udp', 'imap', 'Internet Message Access Protocol', 0),
(0, 144, 'tcp', 'uma', 'Universal Management Architecture', 0),
(0, 144, 'udp', 'uma', 'Universal Management Architecture', 0),
(0, 144, 'udp', 'news', 'NewS window system', 0),
(0, 144, 'tcp', 'news', 'NewS window system', 0),
(0, 145, 'tcp', 'uaac', 'UAAC Protocol', 0),
(0, 145, 'udp', 'uaac', 'UAAC Protocol', 0),
(0, 146, 'tcp', 'iso-tp0', 'ISO-IP0', 0),
(0, 146, 'udp', 'iso-tp0', 'ISO-IP0', 0),
(0, 146, 'tcp', 'Infector', 'Infector', 1),
(0, 146, 'udp', 'Infector', 'Infector', 1),
(0, 147, 'tcp', 'iso-ip', 'ISO-IP', 0),
(0, 147, 'udp', 'iso-ip', 'ISO-IP', 0),
(0, 148, 'tcp', 'jargon', 'Jargon', 0),
(0, 148, 'udp', 'jargon', 'Jargon', 0),
(0, 148, 'tcp', 'cronus', 'CRONUS-SUPPORT', 0),
(0, 148, 'udp', 'cronus', 'CRONUS-SUPPORT', 0),
(0, 149, 'tcp', 'aed-512', 'AED 512 Emulation Service', 0),
(0, 149, 'udp', 'aed-512', 'AED 512 Emulation Service', 0),
(0, 150, 'tcp', 'sql-net', 'SQL-NET', 0),
(0, 150, 'udp', 'sql-net', 'SQL-NET', 0),
(0, 151, 'tcp', 'hems', 'HEMS', 0),
(0, 151, 'udp', 'hems', 'HEMS', 0),
(0, 152, 'tcp', 'bftp', 'Background File Transfer Program', 0),
(0, 152, 'udp', 'bftp', 'Background File Transfer Program', 0),
(0, 153, 'tcp', 'sgmp', 'SGMP', 0),
(0, 153, 'udp', 'sgmp', 'SGMP', 0),
(0, 154, 'tcp', 'netsc-prod', 'NETSC', 0),
(0, 154, 'udp', 'netsc-prod', 'NETSC', 0),
(0, 155, 'tcp', 'netsc-dev', 'NETSC', 0),
(0, 155, 'udp', 'netsc-dev', 'NETSC', 0),
(0, 156, 'tcp', 'sqlsrv', 'SQL Service', 0),
(0, 156, 'udp', 'sqlsrv', 'SQL Service', 0),
(0, 157, 'tcp', 'knet-cmp', 'KNET VM Command Message Protocol', 0),
(0, 157, 'udp', 'knet-cmp', 'KNET VM Command Message Protocol', 0),
(0, 158, 'tcp', 'pcmail-srv', 'PCMail Server', 0),
(0, 158, 'udp', 'pcmail-srv', 'PCMail Server', 0),
(0, 159, 'tcp', 'nss-routing', 'NSS-Routing', 0),
(0, 159, 'udp', 'nss-routing', 'NSS-Routing', 0),
(0, 160, 'tcp', 'sgmp-traps', 'SGMP-TRAPS', 0),
(0, 160, 'udp', 'sgmp-traps', 'SGMP-TRAPS', 0),
(0, 161, 'tcp', 'snmp', 'SNMP', 0),
(0, 161, 'udp', 'snmp', 'SNMP', 0),
(0, 162, 'tcp', 'snmptrap', 'SNMPTRAP', 0),
(0, 162, 'udp', 'snmptrap', 'SNMPTRAP', 0),
(0, 163, 'tcp', 'cmip-man', 'CMIP TCP Manager', 0),
(0, 163, 'udp', 'cmip-man', 'CMIP TCP Manager', 0),
(0, 164, 'tcp', 'cmip-agent', 'CMIP TCP Agent', 0),
(0, 164, 'udp', 'smip-agent', 'CMIP TCP Agent', 0),
(0, 165, 'tcp', 'xns-courier', 'Xerox', 0),
(0, 165, 'udp', 'xns-courier', 'Xerox', 0),
(0, 166, 'tcp', 's-net', 'Sirius Systems', 0),
(0, 166, 'udp', 's-net', 'Sirius Systems', 0),
(0, 166, 'tcp', 'NokNok', 'NokNok', 1),
(0, 167, 'tcp', 'namp', 'NAMP', 0),
(0, 167, 'udp', 'namp', 'NAMP', 0),
(0, 168, 'tcp', 'rsvd', 'RSVD', 0),
(0, 168, 'udp', 'rsvd', 'RSVD', 0),
(0, 169, 'tcp', 'send', 'SEND', 0),
(0, 169, 'udp', 'send', 'SEND', 0),
(0, 170, 'tcp', 'print-srv', 'Network PostScript', 0),
(0, 170, 'udp', 'print-srv', 'Network PostScript', 0),
(0, 170, 'tcp', 'A-trojan', 'A-trojan', 1),
(0, 171, 'tcp', 'multiplex', 'Network Innovations Multiplex', 0),
(0, 171, 'udp', 'multiplex', 'Network Innovations Multiplex', 0),
(0, 172, 'tcp', 'cl-1', 'Network Innovations CL 1', 0),
(0, 172, 'udp', 'cl-1', 'Network Innovations CL 1', 0),
(0, 173, 'tcp', 'xyplex-mux', 'Xyplex', 0),
(0, 173, 'udp', 'xyplex-mux', 'Xyplex', 0),
(0, 174, 'tcp', 'mailq', 'MAILQ', 0),
(0, 174, 'udp', 'mailq', 'MAILQ', 0),
(0, 175, 'tcp', 'vmnet', 'VMNET', 0),
(0, 175, 'udp', 'vmnet', 'VMNET', 0),
(0, 176, 'tcp', 'genrad-mux', 'GENRAD-MUX', 0),
(0, 176, 'udp', 'genrad-mux', 'GENRAD-MUX', 0),
(0, 177, 'tcp', 'xdmcp', 'X Display Manager Control Protocol', 0),
(0, 177, 'udp', 'xdmcp', 'X Display Manager Control Protocol', 0),
(0, 178, 'tcp', 'nextstep', 'NextStep Window Server', 0),
(0, 178, 'udp', 'nextstep', 'NextStep Window Server', 0),
(0, 179, 'tcp', 'bgp', 'Border Gateway Protocol', 0),
(0, 179, 'udp', 'bgp', 'Border Gateway Protocol', 0),
(0, 180, 'tcp', 'ris', 'Intergraph', 0),
(0, 180, 'udp', 'ris', 'Intergraph', 0),
(0, 181, 'tcp', 'unify', 'Unify', 0),
(0, 181, 'udp', 'unify', 'Unify', 0),
(0, 182, 'tcp', 'audit', 'Unisys Audit SITP', 0),
(0, 182, 'udp', 'audit', 'Unisys Audit SITP', 0),
(0, 183, 'tcp', 'ocbinder', 'OCBinder', 0),
(0, 183, 'udp', 'ocbinder', 'OCBinder', 0),
(0, 184, 'tcp', 'ocserver', 'OCServer', 0),
(0, 184, 'udp', 'ocserver', 'OCServer', 0),
(0, 185, 'tcp', 'remote-kis', 'Remote-KIS', 0),
(0, 185, 'udp', 'remote-kis', 'Remote-KIS', 0),
(0, 186, 'tcp', 'kis', 'KIS Protocol', 0),
(0, 186, 'udp', 'kis', 'KIS Protocol', 0),
(0, 187, 'tcp', 'aci', 'Application Communication Interface', 0),
(0, 187, 'udp', 'aci', 'Application Communication Interface', 0),
(0, 188, 'tcp', 'mumps', 'Plus Fives MUMPS', 0),
(0, 188, 'udp', 'mumps', 'Plus Fives MUMPS', 0),
(0, 189, 'tcp', 'qft', 'Queued File Transport', 0),
(0, 189, 'udp', 'qft', 'Queued File Transport', 0),
(0, 190, 'tcp', 'gacp', 'Gateway Access Control Protocol', 0),
(0, 190, 'udp', 'gacp', 'Gateway Access Control Protocol', 0),
(0, 191, 'tcp', 'prospero', 'Prospero Directory Service', 0),
(0, 191, 'udp', 'prospero', 'Prospero Directory Service', 0),
(0, 192, 'tcp', 'osu-nms', 'OSU Network Monitoring System', 0),
(0, 192, 'udp', 'osu-nms', 'OSU Network Monitoring System', 0),
(0, 193, 'tcp', 'srmp', 'Spider Remote Monitoring Protocol', 0),
(0, 193, 'udp', 'srmp', 'Spider Remote Monitoring Protocol', 0),
(0, 194, 'tcp', 'irc', 'Internet Relay Chat Protocol', 0),
(0, 194, 'udp', 'irc', 'Internet Relay Chat Protocol', 0),
(0, 195, 'tcp', 'dn6-nlm-aud', 'DNSIX Network Level Module Audit', 0),
(0, 195, 'udp', 'dn6-nlm-aud', 'DNSIX Network Level Module Audit', 0),
(0, 196, 'tcp', 'dn6-smm-red', 'DNSIX Session Mgt Module Audit Redir', 0),
(0, 196, 'udp', 'dn6-smm-red', 'DNSIX Session Mgt Module Audit Redir', 0),
(0, 197, 'tcp', 'dls', 'Directory Location Service', 0),
(0, 197, 'udp', 'dls', 'Directory Location Service', 0),
(0, 198, 'tcp', 'dls-mon', 'Directory Location Service Monitor', 0),
(0, 198, 'udp', 'dls-mon', 'Directory Location Service Monitor', 0),
(0, 199, 'tcp', 'smux', 'SMUX', 0),
(0, 199, 'udp', 'smux', 'SMUX', 0),
(0, 200, 'tcp', 'src', 'IBM System Resource Controller', 0),
(0, 200, 'udp', 'src', 'IBM System Resource Controller', 0),
(0, 201, 'tcp', 'at-rtmp', 'AppleTalk Routing Maintenance', 0),
(0, 201, 'udp', 'at-rtmp', 'AppleTalk Routing Maintenance', 0),
(0, 202, 'tcp', 'at-nbp', 'AppleTalk Name Binding', 0),
(0, 202, 'udp', 'at-nbp', 'AppleTalk Name Binding', 0),
(0, 203, 'tcp', 'at-3', 'AppleTalk Unused', 0),
(0, 203, 'udp', 'at-3', 'AppleTalk Unused', 0),
(0, 204, 'tcp', 'at-echo', 'AppleTalk Echo', 0),
(0, 204, 'udp', 'at-echo', 'AppleTalk Echo', 0),
(0, 205, 'tcp', 'at-5', 'AppleTalk Unused', 0),
(0, 205, 'udp', 'at-5', 'AppleTalk Unused', 0),
(0, 206, 'tcp', 'at-zis', 'AppleTalk Zone Information', 0),
(0, 206, 'udp', 'at-zis', 'AppleTalk Zone Information', 0),
(0, 207, 'tcp', 'at-7', 'AppleTalk Unused', 0),
(0, 207, 'udp', 'at-7', 'AppleTalk Unused', 0),
(0, 208, 'tcp', 'at-8', 'AppleTalk Unused', 0),
(0, 208, 'udp', 'at-8', 'AppleTalk Unused', 0),
(0, 209, 'tcp', 'qmtp', 'The Quick Mail Transfer Protocol', 0),
(0, 209, 'udp', 'qmtp', 'The Quick Mail Transfer Protocol', 0),
(0, 209, 'tcp', 'tam', 'Trivial Authenticated Mail Protocol', 0),
(0, 209, 'udp', 'tam', 'Trivial Authenticated Mail Protocol', 0),
(0, 210, 'tcp', 'z3950', 'ANSI Z3950', 0),
(0, 210, 'udp', 'z3950', 'ANSI Z3950', 0),
(0, 211, 'tcp', '914c', 'Texas Instruments 914C/G Terminal', 0),
(0, 211, 'udp', '914c', 'Texas Instruments 914C/G Terminal', 0),
(0, 212, 'tcp', 'anet', 'ATEXSSTR', 0),
(0, 212, 'udp', 'anet', 'ATEXSSTR', 0),
(0, 213, 'tcp', 'ipx', 'IPX', 0),
(0, 213, 'udp', 'ipx', 'IPX', 0),
(0, 214, 'tcp', 'vmpwscs', 'VM PWSCS', 0),
(0, 214, 'udp', 'vmpwscs', 'VM PWSCS', 0),
(0, 215, 'tcp', 'softpc', 'Insignia Solutions', 0),
(0, 215, 'udp', 'softpc', 'Insignia Solutions', 0),
(0, 216, 'tcp', 'CAIlic', 'Computer Associates Intl License Server', 0),
(0, 216, 'udp', 'CAIlic', 'Computer Associates Intl License Server', 0),
(0, 216, 'tcp', 'atls', 'Access Technology License Server', 0),
(0, 216, 'udp', 'atls', 'Access Technology License Server', 0),
(0, 217, 'tcp', 'dbase', 'dBASE Unix', 0),
(0, 217, 'udp', 'dbase', 'dBASE Unix', 0),
(0, 218, 'tcp', 'mpp', 'Netix Message Posting Protocol', 0),
(0, 218, 'udp', 'mpp', 'Netix Message Posting Protocol', 0),
(0, 219, 'tcp', 'uarps', 'Unisys ARPs', 0),
(0, 219, 'udp', 'uarps', 'Unisys ARPs', 0),
(0, 220, 'tcp', 'imap3', 'Interactive Mail Access Protocol v3', 0),
(0, 220, 'udp', 'imap3', 'Interactive Mail Access Protocol v3', 0),
(0, 221, 'tcp', 'fln-spx', 'Berkeley rlogind with SPX auth', 0),
(0, 221, 'udp', 'fln-spx', 'Berkeley rlogind with SPX auth', 0),
(0, 222, 'tcp', 'rsh-spx', 'Berkeley rshd with SPX auth', 0),
(0, 222, 'udp', 'rsh-spx', 'Berkeley rshd with SPX auth', 0),
(0, 223, 'tcp', 'cdc', 'Certificate Distribution Center', 0),
(0, 223, 'udp', 'cdc', 'Certificate Distribution Center', 0),
(0, 224, 'tcp', 'masqdialer', 'masqdialer', 0),
(0, 224, 'udp', 'masqdialer', 'masqdialer', 0),
(0, 242, 'tcp', 'direct', 'Direct', 0),
(0, 242, 'udp', 'direct', 'Direct', 0),
(0, 243, 'tcp', 'sur-meas', 'Survey Measurement', 0),
(0, 243, 'udp', 'sur-meas', 'Survey Measurement', 0),
(0, 244, 'tcp', 'inbusiness', 'inbusiness', 0),
(0, 244, 'udp', 'inbusiness', 'inbusiness', 0),
(0, 244, 'tcp', 'dayna', 'Dayna', 0),
(0, 244, 'udp', 'dayna', 'Dayna', 0),
(0, 245, 'tcp', 'link', 'LINK', 0),
(0, 245, 'udp', 'link', 'LINK', 0),
(0, 246, 'tcp', 'dsp3270', 'Display Systems Protocol', 0),
(0, 246, 'udp', 'dsp3270', 'Display Systems Protocol', 0),
(0, 247, 'tcp', 'subntbcst_tftp', 'SUBNTBCST_TFTP', 0),
(0, 247, 'udp', 'subntbcst_tftp', 'SUBNTBCST_TFTP', 0),
(0, 248, 'tcp', 'bhfhs', 'bhfhs', 0),
(0, 248, 'udp', 'bhfhs', 'bhfhs', 0),
(0, 256, 'tcp', 'rap', 'RAP', 0),
(0, 256, 'udp', 'rap', 'RAP', 0),
(0, 256, 'tcp', 'fw1-sync', 'Checkpoint Firewall-1 state table sync', 0),
(0, 257, 'tcp', 'set', 'Secure Electronic Transaction', 0),
(0, 257, 'udp', 'set', 'Secure Electronic Transaction', 0),
(0, 257, 'tcp', 'fw1-log', 'Check Point FW-1/VPN-1 log transfer', 0),
(0, 258, 'tcp', 'yak-chat', 'Yak Winsock Personal Chat', 0),
(0, 258, 'udp', 'yak-chat', 'Yak Winsock Personal Chat', 0),
(0, 258, 'tcp', 'fw1-mgmt', 'Check Point FW-1/VPN-1 management', 0),
(0, 259, 'tcp', 'esro-gen', 'Efficient Short Remote Operations', 0),
(0, 259, 'udp', 'esro-gen', 'Efficient Short Remote Operations', 0),
(0, 259, 'tcp', 'fw1-clntauth', 'Check Point FW-1/VPN-1 client auth', 0),
(0, 259, 'udp', 'fw1-rdp', 'Check Point FW-1/VPN-1 key negotiations over RDP', 0),
(0, 260, 'tcp', 'openport', 'Openport', 0),
(0, 260, 'udp', 'openport', 'Openport', 0),
(0, 260, 'udp', 'fw1-snmp', 'Check Point FW-1/VPN-1 SNMP agent', 0),
(0, 261, 'tcp', 'nsiiops', 'IIOP Name Service over TLS SSL', 0),
(0, 261, 'udp', 'nsiiops', 'IIOP Name Service over TLS SSL', 0),
(0, 261, 'tcp', 'fw1-mgmt', 'Check Point FW-1/VPN-1 Management', 0),
(0, 261, 'tcp', 'fw-snauth', 'Check Point FW-1/VPN-1 session auth', 0),
(0, 262, 'tcp', 'arcisdms', 'Arcisdms', 0),
(0, 262, 'udp', 'arcisdms', 'Arcisdms', 0),
(0, 263, 'tcp', 'hdap', 'HDAP', 0),
(0, 263, 'udp', 'hdap', 'HDAP', 0),
(0, 264, 'tcp', 'bgmp', 'Border Gateway Multicast Protocol', 0),
(0, 264, 'udp', 'bgmp', 'Border Gateway Multicast Protocol', 0),
(0, 264, 'tcp', 'fw1-topo', 'Check Point VPN-1 topology download', 0),
(0, 265, 'tcp', 'x-bone-ctl', 'X-Bone CTL', 0),
(0, 265, 'udp', 'x-bone-ctl', 'X-Bone CTL', 0),
(0, 265, 'tcp', 'fw1-key', 'Check Point VPN-1 public key transfer protocol', 0),
(0, 266, 'tcp', 'sst', 'SCSI on ST', 0),
(0, 266, 'udp', 'sst', 'SCSI on ST', 0),
(0, 267, 'tcp', 'td-service', 'Tobit David Service Layer', 0),
(0, 267, 'udp', 'td-service', 'Tobit David Service Layer', 0),
(0, 268, 'tcp', 'td-replica', 'Tobit David Replica', 0),
(0, 268, 'udp', 'td-replica', 'Tobit David Replica', 0),
(0, 280, 'tcp', 'http-mgmt', 'http-mgmt', 0),
(0, 280, 'udp', 'http-mgmt', 'http-mgmt', 0),
(0, 281, 'tcp', 'personal-link', 'Personal Link', 0),
(0, 281, 'udp', 'personal-link', 'Personal Link', 0),
(0, 282, 'tcp', 'cableport-ax', 'Cable Port A X', 0),
(0, 282, 'udp', 'cableport-ax', 'Cable Port A X', 0),
(0, 283, 'tcp', 'rescap', 'rescap', 0),
(0, 283, 'udp', 'rescap', 'rescap', 0),
(0, 284, 'tcp', 'corerjd', 'corerjd', 0),
(0, 284, 'udp', 'corerjd', 'corerjd', 0),
(0, 286, 'tcp', 'fxp-1', 'FXP-1', 0),
(0, 286, 'udp', 'fxp-1', 'FXP-1', 0),
(0, 287, 'tcp', 'k-block', 'K-BLOCK', 0),
(0, 287, 'udp', 'k-block', 'K-BLOCK', 0),
(0, 308, 'tcp', 'novastorbakcup', 'Novastor Backup', 0),
(0, 308, 'udp', 'novastorbakcup', 'Novastor Backup', 0),
(0, 309, 'tcp', 'entrusttime', 'EntrustTime', 0),
(0, 309, 'udp', 'entrusttime', 'EntrustTime', 0),
(0, 310, 'tcp', 'bhmds', 'bhmds', 0),
(0, 310, 'udp', 'bhmds', 'bhmds', 0),
(0, 311, 'tcp', 'asip-webadmin', 'AppleShare IP WebAdmin', 0),
(0, 311, 'udp', 'asip-webadmin', 'AppleShare IP WebAdmin', 0),
(0, 312, 'tcp', 'vslmp', 'VSLMP', 0),
(0, 312, 'udp', 'vslmp', 'VSLMP', 0),
(0, 313, 'tcp', 'magenta-logic', 'Magenta Logic', 0),
(0, 313, 'udp', 'magenta-logic', 'Magenta Logic', 0),
(0, 314, 'tcp', 'opalis-robot', 'Opalis Robot', 0),
(0, 314, 'udp', 'opalis-robot', 'Opalis Robot', 0),
(0, 315, 'tcp', 'dpsi', 'DPSI', 0),
(0, 315, 'udp', 'dpsi', 'DPSI', 0),
(0, 316, 'tcp', 'decauth', 'decAuth', 0),
(0, 316, 'udp', 'decauth', 'decAuth', 0),
(0, 317, 'tcp', 'zannet', 'Zannet', 0),
(0, 317, 'udp', 'zannet', 'Zannet', 0),
(0, 318, 'tcp', 'pkix-timestamp', 'PKIX TimeStamp', 0),
(0, 318, 'udp', 'pkix-timestamp', 'PKIX TimeStamp', 0),
(0, 319, 'tcp', 'ptp-event', 'PTP Event', 0),
(0, 319, 'udp', 'ptp-event', 'PTP Event', 0),
(0, 320, 'tcp', 'ptp-general', 'PTP General', 0),
(0, 320, 'udp', 'ptp-general', 'PTP General', 0),
(0, 321, 'tcp', 'pip', 'PIP', 0),
(0, 321, 'udp', 'pip', 'PIP', 0),
(0, 322, 'tcp', 'rtsps', 'RTSPS', 0),
(0, 322, 'udp', 'rtsps', 'RTSPS', 0),
(0, 333, 'tcp', 'texar', 'Texar Security Port', 0),
(0, 333, 'udp', 'texar', 'Texar Security Port', 0),
(0, 334, 'tcp', 'Backage', 'Backage', 1),
(0, 344, 'tcp', 'pdap', 'Prospero Data Access Protocol', 0),
(0, 344, 'udp', 'pdap', 'Prospero Data Access Protocol', 0),
(0, 345, 'tcp', 'pawserv', 'Perf Analysis Workbench', 0),
(0, 345, 'udp', 'pawserv', 'Perf Analysis Workbench', 0),
(0, 346, 'tcp', 'zserv', 'Zebra server', 0),
(0, 346, 'udp', 'zserv', 'Zebra server', 0),
(0, 347, 'tcp', 'fatserv', 'Fatmen Server', 0),
(0, 347, 'udp', 'fatserv', 'Fatmen Server', 0),
(0, 348, 'tcp', 'csi-sgwp', 'Cabletron Management Protocol', 0),
(0, 348, 'udp', 'csi-sgwp', 'Cabletron Management Protocol', 0),
(0, 349, 'tcp', 'mftp', 'mftp', 0),
(0, 349, 'udp', 'mftp', 'mftp', 0),
(0, 350, 'tcp', 'matip-type-a', 'MATIP Type A', 0),
(0, 350, 'udp', 'matip-type-a', 'MATIP Type A', 0),
(0, 351, 'tcp', 'matip-type-b', 'MATIP Type B', 0),
(0, 351, 'udp', 'matip-type-b', 'MATIP Type B', 0),
(0, 351, 'tcp', 'bhoetty', 'bhoetty', 0),
(0, 351, 'udp', 'bhoetty', 'bhoetty', 0),
(0, 352, 'tcp', 'dtag-ste-sb', 'DTAG', 0),
(0, 352, 'udp', 'dtag-ste-sb', 'DTAG', 0),
(0, 352, 'udp', 'bhoedap4', 'bhoedap4', 0),
(0, 352, 'tcp', 'bhoedap4', 'bhoedap4', 0),
(0, 353, 'tcp', 'ndsauth', 'NDSAUTH', 0),
(0, 353, 'udp', 'ndsauth', 'NDSAUTH', 0),
(0, 354, 'tcp', 'bh611', 'bh611', 0),
(0, 354, 'udp', 'bh611', 'bh611', 0),
(0, 355, 'tcp', 'datex-asn', 'DATEX-ASN', 0),
(0, 355, 'udp', 'datex-asn', 'DATEX-ASN', 0),
(0, 356, 'tcp', 'cloanto-net-1', 'Cloanto Net 1', 0),
(0, 356, 'udp', 'cloanto-net-1', 'Cloanto Net 1', 0),
(0, 357, 'tcp', 'bhevent', 'bhevent', 0),
(0, 357, 'udp', 'bhevent', 'bhevent', 0),
(0, 358, 'tcp', 'shrinkwrap', 'Shrinkwrap', 0),
(0, 358, 'udp', 'shrinkwrap', 'Shrinkwrap', 0),
(0, 359, 'tcp', 'nsrmp', 'Network Security Risk Management Protocol', 0),
(0, 359, 'udp', 'nsrmp', 'Network Security Risk Management Protocol', 0),
(0, 359, 'tcp', 'tenebris_nts', 'Tenebris Network Trace Service', 0),
(0, 359, 'udp', 'tenebris_nts', 'Tenebris Network Trace Service', 0),
(0, 360, 'tcp', 'scoi2odialog', 'scoi2odialog', 0),
(0, 360, 'udp', 'scoi2odialog', 'scoi2odialog', 0),
(0, 361, 'tcp', 'semantix', 'Semantix', 0),
(0, 361, 'udp', 'semantix', 'Semantix', 0),
(0, 362, 'tcp', 'srssend', 'SRS Send', 0),
(0, 362, 'udp', 'srssend', 'SRS Send', 0),
(0, 363, 'tcp', 'rsvp_tunnel', 'RSVP Tunnel', 0),
(0, 363, 'udp', 'rsvp_tunnel', 'RSVP Tunnel', 0),
(0, 364, 'tcp', 'aurora-cmgr', 'Aurora CMGR', 0),
(0, 364, 'udp', 'aurora-cmgr', 'Aurora CMGR', 0),
(0, 365, 'tcp', 'dtk', 'DTK', 0),
(0, 365, 'udp', 'dtk', 'DTK', 0),
(0, 366, 'tcp', 'odmr', 'ODMR', 0),
(0, 366, 'udp', 'odmr', 'ODMR', 0),
(0, 367, 'tcp', 'mortgageware', 'MortgageWare', 0),
(0, 367, 'udp', 'mortgageware', 'MortgageWare', 0),
(0, 368, 'tcp', 'qbikgdp', 'QbikGDP', 0),
(0, 368, 'udp', 'qbikgdp', 'QbikGDP', 0),
(0, 369, 'tcp', 'rpc2portmap', 'rpc2portmap', 0),
(0, 369, 'udp', 'rpc2portmap', 'rpc2portmap', 0),
(0, 370, 'tcp', 'codaauth2', 'codaauth2', 0),
(0, 370, 'udp', 'codaauth2', 'codaauth2', 0),
(0, 371, 'tcp', 'clearcase', 'Clearcase', 0),
(0, 371, 'udp', 'clearcase', 'Clearcase', 0),
(0, 372, 'tcp', 'ulistproc', 'ListProcessor', 0),
(0, 372, 'udp', 'ulistproc', 'ListProcessor', 0),
(0, 373, 'tcp', 'legent-1', 'Legent Corporation', 0),
(0, 373, 'udp', 'legent-1', 'Legent Corporation', 0),
(0, 374, 'tcp', 'legent-2', 'Legent Corporation', 0),
(0, 374, 'udp', 'legent-2', 'Legent Corporation', 0),
(0, 375, 'tcp', 'hassle', 'Hassle', 0),
(0, 375, 'udp', 'hassle', 'Hassle', 0),
(0, 376, 'tcp', 'nip', 'Amiga Envoy Network Inquiry Proto', 0),
(0, 376, 'udp', 'nip', 'Amiga Envoy Network Inquiry Proto', 0),
(0, 377, 'tcp', 'tnETOS', 'NEC Corporation', 0),
(0, 377, 'udp', 'tnETOS', 'NEC Corporation', 0),
(0, 378, 'tcp', 'dsETOS', 'NEC Corporation', 0),
(0, 378, 'udp', 'dsETOS', 'NEC Corporation', 0),
(0, 379, 'tcp', 'is99c', 'TIA EIA IS-99 modem client', 0),
(0, 379, 'udp', 'is99c', 'TIA EIA IS-99 modem client', 0),
(0, 380, 'tcp', 'is99s', 'TIA EIA IS-99 modem server', 0),
(0, 380, 'udp', 'is99s', 'TIA EIA IS-99 modem server', 0),
(0, 381, 'tcp', 'hp-collector', 'hp performance data collector', 0),
(0, 381, 'udp', 'hp-collector', 'hp performance data collector', 0),
(0, 382, 'tcp', 'hp-managed-node', 'hp performance data managed node', 0),
(0, 382, 'udp', 'hp-managed-node', 'hp performance data managed node', 0),
(0, 383, 'tcp', 'hp-alarm-mgr', 'hp performance data alarm manager', 0),
(0, 383, 'udp', 'hp-alarm-mgr', 'hp performance data alarm manager', 0),
(0, 384, 'tcp', 'arns', 'A Remote Network Server System', 0),
(0, 384, 'udp', 'arns', 'A Remote Network Server System', 0),
(0, 385, 'tcp', 'ibm-app', 'IBM Application', 0),
(0, 385, 'udp', 'ibm-app', 'IBM Application', 0),
(0, 386, 'tcp', 'asa', 'ASA Message Router Object Def', 0),
(0, 386, 'udp', 'asa', 'ASA Message Router Object Def', 0),
(0, 387, 'tcp', 'aurp', 'Appletalk Update-Based Routing Pro', 0),
(0, 387, 'udp', 'aurp', 'Appletalk Update-Based Routing Pro', 0),
(0, 388, 'tcp', 'unidata-ldm', 'Unidata LDM', 0),
(0, 388, 'udp', 'unidata-ldm', 'Unidata LDM', 0),
(0, 389, 'tcp', 'ldap', 'Lightweight Directory Access Protocol', 0),
(0, 389, 'udp', 'ldap', 'Lightweight Directory Access Protocol', 0),
(0, 389, 'tcp', 'ms-ils', 'Microsoft NetMeeting ILS server default port (for', 0),
(0, 390, 'tcp', 'uis', 'UIS', 0),
(0, 390, 'udp', 'uis', 'UIS', 0),
(0, 391, 'tcp', 'synotics-relay', 'SynOptics SNMP Relay Port', 0),
(0, 391, 'udp', 'synotics-relay', 'SynOptics SNMP Relay Port', 0),
(0, 392, 'tcp', 'synotics-broker', 'SynOptics Port Broker Port', 0),
(0, 392, 'udp', 'synotics-broker', 'SynOptics Port Broker Port', 0),
(0, 393, 'tcp', 'meta5', 'Meta5', 0),
(0, 393, 'udp', 'meta5', 'Meta5', 0),
(0, 393, 'tcp', 'dis', 'Data Interpretation System', 0),
(0, 393, 'udp', 'dis', 'Data Interpretation System', 0),
(0, 394, 'tcp', 'embl-ndt', 'EMBL Nucleic Data Transfer', 0),
(0, 394, 'udp', 'embl-ndt', 'EMBL Nucleic Data Transfer', 0),
(0, 395, 'tcp', 'netcp', 'NETscout Control Protocol', 0),
(0, 395, 'udp', 'netcp', 'NETscout Control Protocol', 0),
(0, 396, 'tcp', 'netware-ip', 'Novell Netware over IP', 0),
(0, 396, 'udp', 'netware-ip', 'Novell Netware over IP', 0),
(0, 397, 'tcp', 'mptn', 'Multi Protocol Trans Net', 0),
(0, 397, 'udp', 'mptn', 'Multi Protocol Trans Net', 0),
(0, 398, 'tcp', 'kryptolan', 'Kryptolan', 0),
(0, 398, 'udp', 'kryptolan', 'Kryptolan', 0),
(0, 399, 'tcp', 'iso-tsap-c2', 'ISO Transport Class 2 Non-Control over TCP', 0),
(0, 399, 'udp', 'iso-tsap-c2', 'ISO Transport Class 2 Non-Control over TCP', 0),
(0, 400, 'tcp', 'work-sol', 'Workstation Solutions', 0),
(0, 400, 'udp', 'work-sol', 'Workstation Solutions', 0),
(0, 401, 'tcp', 'ups', 'Uninterruptible Power Supply', 0),
(0, 401, 'udp', 'ups', 'Uninterruptible Power Supply', 0),
(0, 402, 'tcp', 'genie', 'Genie Protocol', 0),
(0, 402, 'udp', 'genie', 'Genie Protocol', 0),
(0, 403, 'tcp', 'decap', 'decap', 0),
(0, 403, 'udp', 'decap', 'decap', 0),
(0, 404, 'tcp', 'nced', 'nced', 0),
(0, 404, 'udp', 'nced', 'nced', 0),
(0, 405, 'tcp', 'ncld', 'ncld', 0),
(0, 405, 'udp', 'ncld', 'ncld', 0),
(0, 406, 'tcp', 'imsp', 'Interactive Mail Support Protocol', 0),
(0, 406, 'udp', 'imsp', 'Interactive Mail Support Protocol', 0),
(0, 407, 'tcp', 'timbuktu', 'Timbuktu', 0),
(0, 407, 'udp', 'timbuktu', 'Timbuktu', 0),
(0, 408, 'tcp', 'prm-sm', 'Prospero Resource Manager Sys Man', 0),
(0, 408, 'udp', 'prm-sm', 'Prospero Resource Manager Sys Man', 0),
(0, 409, 'tcp', 'prm-nm', 'Prospero Resource Manager Node Man', 0),
(0, 409, 'udp', 'prm-nm', 'Prospero Resource Manager Node Man', 0),
(0, 410, 'tcp', 'decladebug', 'DECLadebug Remote Debug Protocol', 0),
(0, 410, 'udp', 'decladebug', 'DECLadebug Remote Debug Protocol', 0),
(0, 411, 'tcp', 'rmt', 'Remote MT Protocol', 0),
(0, 411, 'udp', 'rmt', 'Remote MT Protocol', 0),
(0, 411, 'tcp', 'Backage', 'Backage', 1),
(0, 412, 'tcp', 'synoptics-trap', 'Trap Convention Port', 0),
(0, 412, 'udp', 'synoptics-trap', 'Trap Convention Port', 0),
(0, 413, 'tcp', 'smsp', 'Storage Management Services Protocol', 0),
(0, 413, 'udp', 'smsp', 'Storage Management Services Protocol', 0),
(0, 414, 'tcp', 'infoseek', 'InfoSeek', 0),
(0, 414, 'udp', 'infoseek', 'InfoSeek', 0),
(0, 415, 'tcp', 'bnet', 'BNet', 0),
(0, 415, 'udp', 'bnet', 'BNet', 0),
(0, 416, 'tcp', 'silverplatter', 'Silverplatter', 0),
(0, 416, 'udp', 'silverplatter', 'Silverplatter', 0),
(0, 417, 'tcp', 'onmux', 'Onmux', 0),
(0, 417, 'udp', 'onmux', 'Onmux', 0),
(0, 418, 'tcp', 'hyper-g', 'Hyper-G', 0),
(0, 418, 'udp', 'hyper-g', 'Hyper-G', 0),
(0, 419, 'tcp', 'ariel1', 'Ariel', 0),
(0, 419, 'udp', 'ariel1', 'Ariel', 0),
(0, 420, 'tcp', 'smpte', 'SMPTE', 0),
(0, 420, 'udp', 'smpte', 'SMPTE', 0),
(0, 420, 'tcp', 'Breach', 'Breach', 1),
(0, 420, 'tcp', 'Incognito', 'Incognito', 1),
(0, 421, 'tcp', 'ariel2', 'Ariel', 0),
(0, 421, 'udp', 'ariel2', 'Ariel', 0),
(0, 421, 'tcp', 'TCPWrappers', 'TCP Wrappers', 1),
(0, 421, 'tcp', 'TCPWrapperstrojan', 'TCP Wrappers trojan', 1),
(0, 422, 'tcp', 'ariel3', 'Ariel', 0),
(0, 422, 'udp', 'ariel3', 'Ariel', 0),
(0, 423, 'tcp', 'opc-job-start', 'IBM Operations Planning and Control Start', 0),
(0, 423, 'udp', 'opc-job-start', 'IBM Operations Planning and Control Start', 0),
(0, 424, 'tcp', 'opc-job-track', 'IBM Operations Planning and Control Track', 0),
(0, 424, 'udp', 'opc-job-track', 'IBM Operations Planning and Control Track', 0),
(0, 425, 'tcp', 'icad-el', 'ICAD', 0),
(0, 425, 'udp', 'icad-el', 'ICAD', 0),
(0, 426, 'tcp', 'smartsdp', 'smartsdp', 0),
(0, 426, 'udp', 'smartsdp', 'smartsdp', 0),
(0, 427, 'tcp', 'svrloc', 'Server Location', 0),
(0, 427, 'udp', 'svrloc', 'Server Location', 0),
(0, 428, 'tcp', 'ocs_cmu', 'OCS_CMU', 0),
(0, 428, 'udp', 'ocs_cmu', 'OCS_CMU', 0),
(0, 429, 'tcp', 'ocs_amu', 'OCS_AMU', 0),
(0, 429, 'udp', 'ocs_amu', 'OCS_AMU', 0),
(0, 430, 'tcp', 'utmpsd', 'UTMPSD', 0),
(0, 430, 'udp', 'utmpsd', 'UTMPSD', 0),
(0, 431, 'tcp', 'utmpcd', 'UTMPSD', 0),
(0, 431, 'udp', 'utmpcd', 'UTMPSD', 0),
(0, 432, 'tcp', 'iasd', 'IASD', 0),
(0, 432, 'udp', 'iasd', 'IASD', 0),
(0, 433, 'tcp', 'nnsp', 'Usenet Network News Transfer', 0),
(0, 433, 'udp', 'nnsp', 'Usenet Network News Transfer', 0),
(0, 434, 'tcp', 'mobileip-agent', 'MobileIP-Agent', 0),
(0, 434, 'udp', 'mobileip-agent', 'MobileIP-Agent', 0),
(0, 435, 'tcp', 'mobilip-mn', 'MobileIP-MN', 0),
(0, 435, 'udp', 'mobilip-mn', 'MobileIP-MN', 0),
(0, 436, 'tcp', 'dna-cml', 'DNA-CML', 0),
(0, 436, 'udp', 'dna-cml', 'DNA-CML', 0),
(0, 437, 'tcp', 'comscm', 'comscm', 0),
(0, 437, 'udp', 'comscm', 'comscm', 0),
(0, 438, 'tcp', 'dsfgw', 'dsfgw', 0),
(0, 438, 'udp', 'dsfgw', 'dsfgw', 0),
(0, 439, 'tcp', 'dasp', 'dasp', 0),
(0, 439, 'udp', 'dasp', 'dasp', 0),
(0, 440, 'tcp', 'sgcp', 'sgcp', 0),
(0, 440, 'udp', 'sgcp', 'sgcp', 0),
(0, 441, 'tcp', 'decvms-sysmgt', 'decvms-sysmgt', 0),
(0, 441, 'udp', 'decvms-sysmgt', 'decvms-sysmgt', 0),
(0, 442, 'tcp', 'cvc_hostd', 'cvc_hostd', 0),
(0, 442, 'udp', 'cvc_hostd', 'cvc_hostd', 0),
(0, 443, 'tcp', 'https', 'HTTP protocol over TLS/SSL', 0),
(0, 443, 'udp', 'https', 'HTTP protocol over TLS/SSL', 0),
(0, 444, 'tcp', 'snpp', 'Simple Network Paging Protocol', 0),
(0, 444, 'udp', 'snpp', 'Simple Network Paging Protocol', 0),
(0, 445, 'tcp', 'microsoft-ds', 'Win2k+ Server Message Block', 0),
(0, 445, 'udp', 'microsoft-ds', 'Win2k+ Server Message Block', 0),
(0, 446, 'tcp', 'ddm-rdb', 'DDM-RDB', 0),
(0, 446, 'udp', 'ddm-rdb', 'DDM-RDB', 0),
(0, 447, 'tcp', 'ddm-dfm', 'DDM-RFM', 0),
(0, 447, 'udp', 'ddm-dfm', 'DDM-RFM', 0),
(0, 448, 'tcp', 'ddm-ssl', 'DDM-SSL', 0),
(0, 448, 'udp', 'ddm-ssl', 'DDM-SSL', 0),
(0, 449, 'tcp', 'as-servermap', 'AS Server Mapper', 0),
(0, 449, 'udp', 'as-servermap', 'AS Server Mapper', 0),
(0, 450, 'tcp', 'tserver', 'Computer Supported Telecommunication Applications', 0),
(0, 450, 'udp', 'tserver', 'Computer Supported Telecommunication Applications', 0),
(0, 451, 'tcp', 'sfs-smp-net', 'Cray Network Semaphore server', 0),
(0, 451, 'udp', 'sfs-smp-net', 'Cray Network Semaphore server', 0),
(0, 452, 'tcp', 'sfs-config', 'Cray SFS config server', 0),
(0, 452, 'udp', 'sfs-config', 'Cray SFS config server', 0),
(0, 453, 'tcp', 'creativeserver', 'CreativeServer', 0),
(0, 453, 'udp', 'creativeserver', 'CreativeServer', 0),
(0, 454, 'tcp', 'contentserver', 'ContentServer', 0),
(0, 454, 'udp', 'contentserver', 'ContentServer', 0),
(0, 455, 'tcp', 'creativepartnr', 'CreativePartnr', 0),
(0, 455, 'udp', 'creativepartnr', 'CreativePartnr', 0),
(0, 455, 'tcp', 'FatalConnections', 'Fatal Connections', 1),
(0, 456, 'tcp', 'macon-tcp', 'macon-tcp', 0),
(0, 456, 'udp', 'macon-udp', 'macon-tcp', 0),
(0, 456, 'tcp', 'HackersParadise', 'Hackers Paradise', 1),
(0, 457, 'tcp', 'scohelp', 'scohelp', 0),
(0, 457, 'udp', 'scohelp', 'scohelp', 0),
(0, 458, 'tcp', 'appleqtc', 'apple quick time', 0),
(0, 458, 'udp', 'appleqtc', 'apple quick time', 0),
(0, 459, 'tcp', 'ampr-rcmd', 'ampr-rcmd', 0),
(0, 459, 'udp', 'ampr-rcmd', 'ampr-rcmd', 0),
(0, 460, 'tcp', 'skronk', 'skronk', 0),
(0, 460, 'udp', 'skronk', 'skronk', 0),
(0, 461, 'tcp', 'datasurfsrv', 'DataRampSrv', 0),
(0, 461, 'udp', 'datasurfsrv', 'DataRampSrv', 0),
(0, 462, 'tcp', 'datasurfsrvsec', 'DataRampSrvSec', 0),
(0, 462, 'udp', 'datasurfsrvsec', 'DataRampSrvSec', 0),
(0, 463, 'tcp', 'alpes', 'alpes', 0),
(0, 463, 'udp', 'alpes', 'alpes', 0),
(0, 464, 'tcp', 'kpasswd', 'kpasswd', 0),
(0, 464, 'udp', 'kpasswd', 'kpasswd', 0),
(0, 465, 'tcp', 'urd', 'URL Rendesvous Directory for SSM', 0),
(0, 465, 'udp', 'igmpv3lite', 'IGMP over UDP for SSM', 0),
(0, 465, 'tcp', 'smtps', 'smtp protocol over TLS/SSL (was ssmtp)', 0),
(0, 465, 'udp', 'smtps', 'smtp protocol over TLS/SSL (was ssmtp)', 0),
(0, 466, 'tcp', 'digital-vrc', 'digital-vrc', 0),
(0, 466, 'udp', 'digital-vrc', 'digital-vrc', 0),
(0, 467, 'tcp', 'mylex-mapd', 'mylex-mapd', 0),
(0, 467, 'udp', 'mylex-mapd', 'mylex-mapd', 0),
(0, 468, 'tcp', 'photuris', 'Photuris Key Management', 0),
(0, 468, 'udp', 'photuris', 'Photuris Key Management', 0),
(0, 469, 'tcp', 'rcp', 'Radio Control Protocol', 0),
(0, 469, 'udp', 'rcp', 'Radio Control Protocol', 0),
(0, 470, 'tcp', 'scx-proxy', 'scx-proxy', 0),
(0, 470, 'udp', 'scx-proxy', 'scx-proxy', 0),
(0, 471, 'tcp', 'mondex', 'Mondex', 0),
(0, 471, 'udp', 'mondex', 'Mondex', 0),
(0, 472, 'tcp', 'ljk-login', 'ljk-login', 0),
(0, 472, 'udp', 'ljk-login', 'ljk-login', 0),
(0, 473, 'tcp', 'hybrid-pop', 'hybrid-pop', 0),
(0, 473, 'udp', 'hybrid-pop', 'hybrid-pop', 0),
(0, 474, 'tcp', 'tn-tl-w1', 'tn-t1-w1', 0),
(0, 474, 'udp', 'tn-tl-w2', 'tn-t1-w2', 0),
(0, 475, 'tcp', 'tcpnethaspsrv', 'tcpnethaspsrv', 0),
(0, 475, 'udp', 'tcpnethaspsrv', 'tcpnethaspsrv', 0),
(0, 476, 'tcp', 'tn-tl-fd1', 'tn-t1-fd1', 0),
(0, 476, 'udp', 'tn-tl-fd1', 'tn-t1-fd1', 0),
(0, 477, 'tcp', 'ss7ns', 'ss7ns', 0),
(0, 477, 'udp', 'ss7ns', 'ss7ns', 0),
(0, 478, 'tcp', 'spsc', 'spsc', 0),
(0, 478, 'udp', 'spsc', 'spsc', 0),
(0, 479, 'tcp', 'iafserver', 'iafserver', 0),
(0, 479, 'udp', 'iafserver', 'iafserver', 0),
(0, 480, 'tcp', 'iafdbase', 'iafdbase', 0),
(0, 480, 'udp', 'iafdbase', 'iafdbase', 0),
(0, 480, 'tcp', 'loadsrv', 'loadsrv', 0),
(0, 481, 'tcp', 'ph', 'Ph service', 0),
(0, 481, 'udp', 'ph', 'Ph service', 0),
(0, 481, 'tcp', 'dvs', 'dvs', 0),
(0, 482, 'tcp', 'bgs-nsi', 'bgs-nsi', 0),
(0, 482, 'udp', 'bgs-nsi', 'bgs-nsi', 0),
(0, 482, 'udp', 'xlog', 'xlog', 0),
(0, 483, 'tcp', 'ulpnet', 'ulpnet', 0),
(0, 483, 'udp', 'ulpnet', 'ulpnet', 0),
(0, 484, 'tcp', 'integra-sme', 'Integra Software Management Environment', 0),
(0, 484, 'udp', 'integra-sme', 'Integra Software Management Environment', 0),
(0, 485, 'tcp', 'powerburst', 'Air Soft Power Burst', 0),
(0, 485, 'udp', 'powerburst', 'Air Soft Power Burst', 0),
(0, 486, 'tcp', 'avian', 'avian', 0),
(0, 486, 'udp', 'avian', 'avian', 0),
(0, 486, 'tcp', 'sstats', 'sstats', 0),
(0, 487, 'tcp', 'saft', 'saft Simple Asynchronous File Transfer', 0),
(0, 487, 'udp', 'saft', 'saft Simple Asynchronous File Transfer', 0),
(0, 488, 'tcp', 'gss-http', 'gss-http', 0),
(0, 488, 'udp', 'gss-http', 'gss-http', 0),
(0, 489, 'tcp', 'nest-protocol', 'nest-protocol', 0),
(0, 489, 'udp', 'nest-protocol', 'nest-protocol', 0),
(0, 490, 'tcp', 'micom-pfs', 'micom-pfs', 0),
(0, 490, 'udp', 'micom-pfs', 'micom-pfs', 0),
(0, 491, 'tcp', 'go-login', 'go-login', 0),
(0, 491, 'udp', 'go-login', 'go-login', 0),
(0, 492, 'tcp', 'ticf-1', 'Transport Independent Convergence for FNA', 0),
(0, 492, 'udp', 'ticf-1', 'Transport Independent Convergence for FNA', 0),
(0, 493, 'tcp', 'ticf-2', 'Transport Independent Convergence for FNA', 0),
(0, 493, 'udp', 'ticf-2', 'Transport Independent Convergence for FNA', 0),
(0, 494, 'tcp', 'pov-ray', 'POV-Ray', 0),
(0, 494, 'udp', 'pov-ray', 'POV-Ray', 0),
(0, 495, 'tcp', 'intecourier', 'intecourier', 0),
(0, 495, 'udp', 'intecourier', 'intecourier', 0),
(0, 496, 'tcp', 'pim-rp-disc', 'PIM-RP-DISC', 0),
(0, 496, 'udp', 'pim-rp-disc', 'PIM-RP-DISC', 0),
(0, 497, 'tcp', 'dantz', 'dantz', 0),
(0, 497, 'udp', 'dantz', 'dantz', 0),
(0, 498, 'tcp', 'siam', 'siam', 0),
(0, 498, 'udp', 'siam', 'siam', 0),
(0, 499, 'tcp', 'iso-ill', 'ISO ILL Protocol', 0),
(0, 499, 'udp', 'iso-ill', 'ISO ILL Protocol', 0),
(0, 500, 'tcp', 'isakmp', 'isakmp', 0),
(0, 500, 'udp', 'isakmp', 'isakmp', 0),
(0, 501, 'tcp', 'stmf', 'STMF', 0),
(0, 501, 'udp', 'stmf', 'STMF', 0),
(0, 502, 'tcp', 'asa-appl-proto', 'asa-appl-proto', 0),
(0, 502, 'udp', 'asa-appl-proto', 'asa-appl-proto', 0),
(0, 503, 'tcp', 'intrinsa', 'Intrinsa', 0),
(0, 503, 'udp', 'intrinsa', 'Intrinsa', 0),
(0, 504, 'tcp', 'citadel', 'citadel', 0),
(0, 504, 'udp', 'citadel', 'citadel', 0),
(0, 505, 'tcp', 'mailbox-lm', 'mailbox-lm', 0),
(0, 505, 'udp', 'mailbox-lm', 'mailbox-lm', 0),
(0, 506, 'tcp', 'ohimsrv', 'ohimsrv', 0),
(0, 506, 'udp', 'ohimsrv', 'ohimsrv', 0),
(0, 507, 'tcp', 'crs', 'crs', 0),
(0, 507, 'udp', 'crs', 'crs', 0),
(0, 508, 'tcp', 'xvttp', 'xvttp', 0),
(0, 508, 'udp', 'xvttp', 'xvttp', 0),
(0, 509, 'tcp', 'snare', 'snare', 0),
(0, 509, 'udp', 'snare', 'snare', 0),
(0, 510, 'tcp', 'fcp', 'FirstClass Protocol', 0),
(0, 510, 'udp', 'fcp', 'FirstClass Protocol', 0),
(0, 510, 'tcp', 't0rnkit-sshd', 't0rnkit sshd', 2),
(0, 511, 'tcp', 'passgo', 'PassGo', 0),
(0, 511, 'udp', 'passgo', 'PassGo', 0),
(0, 511, 'tcp', 'T0rnRootkit', 'T0rn Rootkit', 1),
(0, 512, 'tcp', 'exec', 'BSD rexecd(8)', 0),
(0, 512, 'udp', 'biff', 'biff', 0),
(0, 512, 'udp', 'comsat', 'comsat', 0),
(0, 513, 'tcp', 'login', 'BSD rlogind(8)', 0),
(0, 513, 'udp', 'who', 'BSD rwhod(8)', 0),
(0, 513, 'tcp', 'Grlogin', 'Grlogin', 1),
(0, 514, 'tcp', 'shell', 'BSD rshd(8)', 0),
(0, 514, 'udp', 'syslog', 'syslog', 0),
(0, 514, 'tcp', 'RPCBackdoor', 'RPC Backdoor', 2),
(0, 515, 'tcp', 'printer', 'spooler', 0),
(0, 515, 'udp', 'printer', 'spooler', 0),
(0, 515, 'tcp', 'lpdw0rm', 'lpdw0rm', 1),
(0, 515, 'tcp', 'Ramen', 'Ramen', 1),
(0, 516, 'tcp', 'videotex', 'videotex', 0),
(0, 516, 'udp', 'videotex', 'videotex', 0),
(0, 517, 'tcp', 'talk', 'talk', 0),
(0, 517, 'udp', 'talk', 'talk', 0),
(0, 518, 'tcp', 'ntalk', 'ntalk', 0),
(0, 518, 'udp', 'ntalk', 'ntalk', 0),
(0, 519, 'tcp', 'utime', 'unixtime', 0),
(0, 519, 'udp', 'utime', 'unixtime', 0),
(0, 520, 'tcp', 'efs', 'extended file name server', 0),
(0, 520, 'udp', 'route', 'router routed - RIP', 0),
(0, 521, 'tcp', 'ripng', 'ripng', 0),
(0, 521, 'udp', 'ripng', 'ripng', 0),
(0, 522, 'tcp', 'ulp', 'ULP', 0),
(0, 522, 'udp', 'ulp', 'ULP', 0),
(0, 523, 'tcp', 'ibm-db2', 'IBM-DB2', 0),
(0, 523, 'udp', 'ibm-db2', 'IBM-DB2', 0),
(0, 524, 'tcp', 'ncp', 'NCP', 0),
(0, 524, 'udp', 'ncp', 'NCP', 0),
(0, 525, 'tcp', 'timed', 'timeserver', 0),
(0, 525, 'udp', 'timed', 'timeserver', 0),
(0, 526, 'tcp', 'tempo', 'newdate', 0),
(0, 526, 'udp', 'tempo', 'newdate', 0),
(0, 527, 'tcp', 'stx', 'Stock IXChange', 0),
(0, 527, 'udp', 'stx', 'Stock IXChange', 0),
(0, 528, 'tcp', 'custix', 'Customer IXChange', 0),
(0, 528, 'udp', 'custix', 'Customer IXChange', 0),
(0, 529, 'tcp', 'irc-serv', 'IRC-SERV', 0),
(0, 529, 'udp', 'irc-serv', 'IRC-SERV', 0),
(0, 530, 'tcp', 'courier', 'rpc', 0),
(0, 530, 'udp', 'courier', 'rpc', 0),
(0, 531, 'tcp', 'conference', 'chat', 0),
(0, 531, 'udp', 'conference', 'chat', 0),
(0, 531, 'tcp', 'Net666', 'Net666', 1),
(0, 531, 'tcp', 'Rasmin', 'Rasmin', 1),
(0, 532, 'tcp', 'netnews', 'readnews', 0),
(0, 532, 'udp', 'netnews', 'readnews', 0),
(0, 532, 'tcp', 'ibm-db2', 'IBM DB2 admin listener', 0),
(0, 533, 'tcp', 'netwall', 'netwall for emergency broadcasts', 0),
(0, 533, 'udp', 'netwall', 'netwall for emergency broadcasts', 0),
(0, 534, 'tcp', 'mm-admin', 'MegaMedia Admin', 0),
(0, 534, 'udp', 'mm-admin', 'MegaMedia Admin', 0),
(0, 535, 'tcp', 'iiop', 'iiop', 0),
(0, 535, 'udp', 'iiop', 'iiop', 0),
(0, 536, 'tcp', 'opalis-rdv', 'opalis-rdv', 0),
(0, 536, 'udp', 'opalis-rdv', 'opalis-rdv', 0),
(0, 537, 'tcp', 'nmsp', 'Networked Media Streaming Protocol', 0),
(0, 537, 'udp', 'nmsp', 'Networked Media Streaming Protocol', 0),
(0, 538, 'tcp', 'gdomap', 'gdomap', 0),
(0, 538, 'udp', 'gdomap', 'gdomap', 0),
(0, 539, 'tcp', 'apertus-ldp', 'Apertus Technologies Load Determination', 0),
(0, 539, 'udp', 'apertus-ldp', 'Apertus Technologies Load Determination', 0),
(0, 540, 'tcp', 'uucp', 'uucpd', 0),
(0, 540, 'udp', 'uucp', 'uucpd', 0),
(0, 541, 'tcp', 'uucp-rlogin', 'uucp-rlogin', 0),
(0, 541, 'udp', 'uucp-rlogin', 'uucp-rlogin', 0),
(0, 542, 'tcp', 'commerce', 'commerce', 0),
(0, 542, 'udp', 'commerce', 'commerce', 0),
(0, 543, 'tcp', 'klogin', 'klogin', 0),
(0, 543, 'udp', 'klogin', 'klogin', 0),
(0, 544, 'tcp', 'kshell', 'krcmd', 0),
(0, 544, 'udp', 'kshell', 'krcmd', 0),
(0, 545, 'tcp', 'appleqtcsrvr', 'appleqtcsrvr', 0),
(0, 545, 'udp', 'appleqtcsrvr', 'appleqtcsrvr', 0),
(0, 545, 'tcp', 'ekshell', 'Kerberos encrypted remote shell UNAME?', 0),
(0, 546, 'tcp', 'dhcpv6-client', 'DHCPv6 Client', 0),
(0, 546, 'udp', 'dhcpv6-client', 'DHCPv6 Client', 0),
(0, 547, 'tcp', 'dhcpv6-server', 'DHCPv6 Server', 0),
(0, 547, 'udp', 'dhcpv6-server', 'DHCPv6 Server', 0),
(0, 548, 'tcp', 'afpovertcp', 'AFP over TCP', 0),
(0, 548, 'udp', 'afpovertcp', 'AFP over TCP', 0),
(0, 549, 'tcp', 'idfp', 'IDFP', 0),
(0, 549, 'udp', 'idfp', 'IDFP', 0),
(0, 550, 'tcp', 'new-rwho', 'new-who', 0),
(0, 550, 'udp', 'new-rwho', 'new-who', 0),
(0, 551, 'tcp', 'cybercash', 'cybercash', 0),
(0, 551, 'udp', 'cybercash', 'cybercash', 0),
(0, 552, 'tcp', 'deviceshare', 'deviceshare', 0),
(0, 552, 'udp', 'deviceshare', 'deviceshare', 0),
(0, 553, 'tcp', 'pirp', 'pirp', 0),
(0, 553, 'udp', 'pirp', 'pirp', 0),
(0, 554, 'tcp', 'rtsp', 'Real Time Stream Control Protocol', 0),
(0, 554, 'udp', 'rtsp', 'Real Time Stream Control Protocol', 0),
(0, 555, 'tcp', 'dsf', 'dsf', 0),
(0, 555, 'udp', 'dsf', 'dsf', 0),
(0, 555, 'tcp', '711trojan', '711 trojan (Seven Eleven)', 1),
(0, 555, 'tcp', 'IniKiller', 'Ini-Killer', 1),
(0, 555, 'tcp', 'NetAdministrator', 'Net Administrator', 1),
(0, 555, 'tcp', 'Phase-0', 'Phase-0', 1),
(0, 555, 'tcp', 'PhaseZero', 'Phase Zero', 1),
(0, 555, 'tcp', 'StealthSpy', 'Stealth Spy', 1),
(0, 556, 'tcp', 'remotefs', 'rfs server  Brunhoff remote filesystem', 0),
(0, 556, 'udp', 'remotefs', 'rfs server  Brunhoff remote filesystem', 0),
(0, 557, 'tcp', 'openvms-sysipc', 'openvms-sysipc', 0),
(0, 557, 'udp', 'openvms-sysipc', 'openvms-sysipc', 0),
(0, 558, 'tcp', 'sdnskmp', 'SDNSKMP', 0),
(0, 558, 'udp', 'sdnskmp', 'SDNSKMP', 0),
(0, 559, 'tcp', 'teedtap', 'TEEDTAP', 0),
(0, 559, 'udp', 'teedtap', 'TEEDTAP', 0),
(0, 560, 'tcp', 'rmonitor', 'rmonitord', 0),
(0, 560, 'udp', 'rmonitor', 'rmonitord', 0),
(0, 561, 'tcp', 'monitor', 'monitor', 0),
(0, 561, 'udp', 'monitor', 'monitor', 0),
(0, 562, 'tcp', 'chshell', 'chcmd', 0),
(0, 562, 'udp', 'chshell', 'chcmd', 0),
(0, 563, 'tcp', 'nntps', 'nntp protocol over TLS SSL (was snntp)', 0),
(0, 563, 'udp', 'nntps', 'nntp protocol over TLS SSL (was snntp)', 0),
(0, 563, 'tcp', 'snews', 'snews', 0),
(0, 563, 'udp', 'snews', 'snews', 0),
(0, 564, 'tcp', '9pfs', 'plan 9 file service', 0),
(0, 564, 'udp', '9pfs', 'plan 9 file service', 0),
(0, 565, 'tcp', 'whoami', 'whoami', 0),
(0, 565, 'udp', 'whoami', 'whoami', 0),
(0, 566, 'tcp', 'streettalk', 'streettalk', 0),
(0, 566, 'udp', 'streettalk', 'streettalk', 0),
(0, 567, 'tcp', 'banyan-rpc', 'banyan-rpc', 0),
(0, 567, 'udp', 'banyan-rpc', 'banyan-rpc', 0),
(0, 568, 'tcp', 'ms-shuttle', 'Microsoft shuttle', 0),
(0, 568, 'udp', 'ms-shuttle', 'Microsoft shuttle', 0),
(0, 569, 'tcp', 'ms-rome', 'Microsoft rome', 0),
(0, 569, 'udp', 'ms-rome', 'Microsoft rome', 0),
(0, 570, 'tcp', 'meter', 'demon', 0),
(0, 570, 'udp', 'meter', 'demon', 0),
(0, 571, 'tcp', 'meter', 'udemon', 0),
(0, 571, 'udp', 'meter', 'udemon', 0),
(0, 572, 'tcp', 'sonar', 'sonar', 0),
(0, 572, 'udp', 'sonar', 'sonar', 0),
(0, 573, 'tcp', 'banyan-vip', 'banyan-vip', 0),
(0, 573, 'udp', 'banyan-vip', 'banyan-vip', 0),
(0, 574, 'tcp', 'ftp-agent', 'FTP Software Agent System', 0),
(0, 574, 'udp', 'ftp-agent', 'FTP Software Agent System', 0),
(0, 575, 'tcp', 'vemmi', 'vemmi', 0),
(0, 575, 'udp', 'vemmi', 'vemmi', 0),
(0, 576, 'tcp', 'ipcd', 'ipcd', 0),
(0, 576, 'udp', 'ipcd', 'ipcd', 0),
(0, 577, 'tcp', 'vnas', 'vnas', 0),
(0, 577, 'udp', 'vnas', 'vnas', 0),
(0, 578, 'tcp', 'ipdd', 'ipdd', 0),
(0, 578, 'udp', 'ipdd', 'ipdd', 0),
(0, 579, 'tcp', 'decbsrv', 'decbsrv', 0),
(0, 579, 'udp', 'decbsrv', 'decbsrv', 0),
(0, 580, 'tcp', 'sntp-heartbeat', 'SNTP HEARTBEAT', 0),
(0, 580, 'udp', 'sntp-heartbeat', 'SNTP HEARTBEAT', 0),
(0, 581, 'tcp', 'bdp', 'Bundle Discovery Protocol', 0),
(0, 581, 'udp', 'bdp', 'Bundle Discovery Protocol', 0),
(0, 582, 'tcp', 'scc-security', 'SCC Security', 0),
(0, 582, 'udp', 'scc-security', 'SCC Security', 0),
(0, 583, 'tcp', 'philips-vc', 'Philips Video-Conferencing', 0),
(0, 583, 'udp', 'philips-vc', 'Philips Video-Conferencing', 0),
(0, 584, 'tcp', 'keyserver', 'Key Server', 0),
(0, 584, 'udp', 'keyserver', 'Key Server', 0),
(0, 585, 'tcp', 'imap4-ssl', 'IMAP4+SSL', 0),
(0, 585, 'udp', 'imap4-ssl', 'IMAP4+SSL', 0),
(0, 586, 'tcp', 'password-chg', 'Password Change', 0),
(0, 586, 'udp', 'password-chg', 'Password Change', 0),
(0, 587, 'tcp', 'submission', 'Submission', 0),
(0, 587, 'udp', 'submission', 'Submission', 0),
(0, 588, 'tcp', 'cal', 'CAL', 0),
(0, 588, 'udp', 'cal', 'CAL', 0),
(0, 589, 'tcp', 'eyelink', 'EyeLink', 0),
(0, 589, 'udp', 'eyelink', 'EyeLink', 0),
(0, 590, 'tcp', 'tns-cml', 'TNS CML', 0),
(0, 590, 'udp', 'tns-cml', 'TNS CML', 0),
(0, 591, 'tcp', 'http-alt', 'FileMaker  Inc - HTTP Alternate (see Port 80)', 0),
(0, 591, 'udp', 'http-alt', 'FileMaker  Inc - HTTP Alternate (see Port 80)', 0),
(0, 592, 'tcp', 'eudora-set', 'Eudora Set', 0),
(0, 592, 'udp', 'eudora-set', 'Eudora Set', 0),
(0, 593, 'tcp', 'http-rpc-epmap', 'HTTP RPC Ep Map', 0),
(0, 593, 'udp', 'http-rpc-epmap', 'HTTP RPC Ep Map', 0),
(0, 594, 'tcp', 'tpip', 'TPIP', 0),
(0, 594, 'udp', 'tpip', 'TPIP', 0),
(0, 595, 'tcp', 'cab-protocol', 'CAB Protocol', 0),
(0, 595, 'udp', 'cab-protocol', 'CAB Protocol', 0),
(0, 596, 'tcp', 'smsd', 'SMSD', 0),
(0, 596, 'udp', 'smsd', 'SMSD', 0),
(0, 597, 'tcp', 'ptcnameservice', 'PTC Name Service', 0),
(0, 597, 'udp', 'ptcnameservice', 'PTC Name Service', 0),
(0, 598, 'tcp', 'sco-websrvrmg3', 'SCO Web Server Manager 3', 0),
(0, 598, 'udp', 'sco-websrvrmg3', 'SCO Web Server Manager 3', 0),
(0, 599, 'tcp', 'acp', 'Aeolon Core Protocol', 0),
(0, 599, 'udp', 'acp', 'Aeolon Core Protocol', 0),
(0, 600, 'tcp', 'ipcserver', 'Sun IPC server', 0),
(0, 600, 'udp', 'ipcserver', 'Sun IPC server', 0),
(0, 600, 'tcp', 'Sadmind', 'Sadmind', 1),
(0, 601, 'tcp', 'syslog-conn', 'Reliable Syslog Service', 0),
(0, 601, 'udp', 'syslog-conn', 'Reliable Syslog Service', 0),
(0, 602, 'tcp', 'xmlrpc-beep', 'XML-RPC over BEEP', 0),
(0, 602, 'udp', 'xmlrpc-beep', 'XML-RPC over BEEP', 0),
(0, 603, 'tcp', 'idxp', 'IDXP', 0),
(0, 603, 'udp', 'idxp', 'IDXP', 0),
(0, 604, 'tcp', 'tunnel', 'TUNNEL', 0),
(0, 604, 'udp', 'tunnel', 'TUNNEL', 0),
(0, 605, 'tcp', 'soap-beep', 'SOAP over BEEP', 0),
(0, 605, 'udp', 'soap-beep', 'SOAP over BEEP', 0),
(0, 605, 'tcp', 'SecretService', 'Secret Service', 1),
(0, 606, 'tcp', 'urm', 'Cray Unified Resource Manager', 0),
(0, 606, 'udp', 'urm', 'Cray Unified Resource Manager', 0),
(0, 607, 'tcp', 'nqs', 'nqs', 0),
(0, 607, 'udp', 'nqs', 'nqs', 0),
(0, 608, 'tcp', 'sift-uft', 'Sender-Initiated/Unsolicited File Transfer', 0),
(0, 608, 'udp', 'sift-uft', 'Sender-Initiated/Unsolicited File Transfer', 0),
(0, 609, 'tcp', 'npmp-trap', 'npmp-trap', 0),
(0, 609, 'udp', 'npmp-trap', 'npmp-trap', 0),
(0, 610, 'tcp', 'npmp-local', 'npmp-local', 0),
(0, 610, 'udp', 'npmp-local', 'npmp-local', 0),
(0, 611, 'tcp', 'npmp-gui', 'npmp-gui', 0),
(0, 611, 'udp', 'npmp-gui', 'npmp-gui', 0),
(0, 612, 'tcp', 'hmmp-ind', 'HMMP Indication', 0),
(0, 612, 'udp', 'hmmp-ind', 'HMMP Indication', 0),
(0, 613, 'tcp', 'hmmp-op', 'HMMP Operation', 0),
(0, 613, 'udp', 'hmmp-op', 'HMMP Operation', 0),
(0, 614, 'tcp', 'sshell', 'SSLshell', 0),
(0, 614, 'udp', 'sshell', 'SSLshell', 0),
(0, 615, 'tcp', 'sco-inetmgr', 'Internet Configuration Manager', 0),
(0, 615, 'udp', 'sco-inetmgr', 'Internet Configuration Manager', 0),
(0, 616, 'tcp', 'sco-sysmgr', 'SCO System Administration Server', 0),
(0, 616, 'udp', 'sco-sysmgr', 'SCO System Administration Server', 0),
(0, 617, 'tcp', 'sco-dtmgr', 'SCO Desktop Administration Server', 0),
(0, 617, 'udp', 'sco-dtmgr', 'SCO Desktop Administration Server', 0),
(0, 618, 'tcp', 'dei-icda', 'DEI-ICDA', 0),
(0, 618, 'udp', 'dei-icda', 'DEI-ICDA', 0),
(0, 619, 'tcp', 'compaq-evm', 'Compaq EVM', 0),
(0, 619, 'udp', 'compaq-evm', 'Compaq EVM', 0),
(0, 620, 'tcp', 'sco-websrvrmgr', 'SCO WebServer Manager', 0),
(0, 620, 'udp', 'sco-websrvrmgr', 'SCO WebServer Manager', 0),
(0, 621, 'tcp', 'escp-ip', 'ESCP', 0),
(0, 621, 'udp', 'escp-ip', 'ESCP', 0),
(0, 622, 'tcp', 'collaborator', 'Collaborator', 0),
(0, 622, 'udp', 'collaborator', 'Collaborator', 0),
(0, 623, 'tcp', 'asf-rmcp', 'ASF Remote Management and Control Protocol', 0),
(0, 623, 'udp', 'asf-rmcp', 'ASF Remote Management and Control Protocol', 0),
(0, 623, 'tcp', 'aux_bus_shunt', 'Aux Bus Shunt', 0),
(0, 623, 'udp', 'aux_bus_shunt', 'Aux Bus Shunt', 0),
(0, 624, 'tcp', 'cryptoadmin', 'Crypto Admin', 0),
(0, 624, 'udp', 'cryptoadmin', 'Crypto Admin', 0),
(0, 625, 'tcp', 'dec_dlm', 'DEC DLM', 0),
(0, 625, 'udp', 'dec_dlm', 'DEC DLM', 0),
(0, 626, 'tcp', 'asia', 'ASIA', 0),
(0, 626, 'udp', 'asia', 'ASIA', 0),
(0, 627, 'tcp', 'passgo-tivoli', 'PassGo Tivoli', 0),
(0, 627, 'udp', 'passgo-tivoli', 'PassGo Tivoli', 0),
(0, 628, 'tcp', 'qmqp', 'QMQP (qmail)', 0),
(0, 628, 'udp', 'qmqp', 'QMQP (qmail)', 0),
(0, 629, 'tcp', '3com-amp3', '3Com AMP3', 0),
(0, 629, 'udp', '3com-amp3', '3Com AMP3', 0),
(0, 630, 'tcp', 'rda', 'RDA', 0),
(0, 630, 'udp', 'rda', 'RDA', 0),
(0, 631, 'tcp', 'ipp', 'Internet Printing Protocol', 0),
(0, 631, 'udp', 'ipp', 'Internet Printing Protocol', 0),
(0, 632, 'tcp', 'bmpp', 'bmpp', 0),
(0, 632, 'udp', 'bmpp', 'bmpp', 0),
(0, 633, 'tcp', 'servstat', 'Service Status update (Sterling Software)', 0),
(0, 633, 'udp', 'servstat', 'Service Status update (Sterling Software)', 0),
(0, 634, 'tcp', 'ginad', 'ginad', 0),
(0, 634, 'udp', 'ginad', 'ginad', 0),
(0, 635, 'tcp', 'rlzdbase', 'RLZ DBase', 0),
(0, 635, 'udp', 'rlzdbase', 'RLZ DBase', 0),
(0, 635, 'udp', 'mount', 'NFS Mount Service', 0),
(0, 636, 'tcp', 'ldaps', 'ldap protocol over TLS/SSL (was sldap)', 0),
(0, 636, 'udp', 'ldaps', 'ldap protocol over TLS/SSL (was sldap)', 0),
(0, 637, 'tcp', 'lanserver', 'lanserver', 0),
(0, 637, 'udp', 'lanserver', 'lanserver', 0),
(0, 638, 'tcp', 'mcns-sec', 'mcns-sec', 0),
(0, 638, 'udp', 'mcns-sec', 'mcns-sec', 0),
(0, 639, 'tcp', 'msdp', 'MSDP', 0),
(0, 639, 'udp', 'msdp', 'MSDP', 0),
(0, 640, 'tcp', 'entrust-sps', 'entrust-sps', 0),
(0, 640, 'udp', 'entrust-sps', 'entrust-sps', 0),
(0, 640, 'udp', 'pcnfs', 'PC-NFS DOS Authentication', 0),
(0, 641, 'tcp', 'repcmd', 'repcmd', 0),
(0, 641, 'udp', 'repcmd', 'repcmd', 0),
(0, 642, 'tcp', 'esro-emsdp', 'ESRO-EMSDP V13', 0),
(0, 642, 'udp', 'esro-emsdp', 'ESRO-EMSDP V13', 0),
(0, 643, 'tcp', 'sanity', 'SANity', 0),
(0, 643, 'udp', 'sanity', 'SANity', 0),
(0, 644, 'tcp', 'dwr', 'dwr', 0),
(0, 644, 'udp', 'dwr', 'dwr', 0),
(0, 645, 'tcp', 'pssc', 'PSSC', 0),
(0, 645, 'udp', 'pssc', 'PSSC', 0),
(0, 646, 'tcp', 'ldp', 'LDP', 0),
(0, 646, 'udp', 'ldp', 'LDP', 0),
(0, 647, 'tcp', 'dhcp-failover', 'DHCP Failover', 0),
(0, 647, 'udp', 'dhcp-failover', 'DHCP Failover', 0),
(0, 648, 'tcp', 'rrp', 'Registry Registrar Protocol (RRP)', 0),
(0, 648, 'udp', 'rrp', 'Registry Registrar Protocol (RRP)', 0),
(0, 649, 'tcp', 'cadview-3d', 'Cadview-3d - streaming 3d models over the internet', 0),
(0, 649, 'udp', 'cadview-3d', 'Cadview-3d - streaming 3d models over the internet', 0),
(0, 649, 'tcp', 'aminet', 'Aminet', 0),
(0, 649, 'udp', 'aminet', 'Aminet', 0),
(0, 650, 'tcp', 'obex', 'OBEX', 0),
(0, 650, 'udp', 'obex', 'OBEX', 0),
(0, 650, 'udp', 'bwnfs', 'BW-NFS DOS Authentication', 0),
(0, 651, 'tcp', 'ieee-mms', 'IEEE MMS', 0),
(0, 651, 'udp', 'ieee-mms', 'IEEE MMS', 0),
(0, 652, 'tcp', 'hello-port', 'HELLO_PORT', 0),
(0, 652, 'udp', 'hello-port', 'HELLO_PORT', 0),
(0, 653, 'tcp', 'repscmd', 'RepCmd', 0),
(0, 653, 'udp', 'repscmd', 'RepCmd', 0),
(0, 654, 'tcp', 'aodv', 'AODV', 0),
(0, 654, 'udp', 'aodv', 'AODV', 0),
(0, 655, 'tcp', 'tinc', 'TINC', 0),
(0, 655, 'udp', 'tinc', 'TINC', 0),
(0, 656, 'tcp', 'spmp', 'SPMP', 0),
(0, 656, 'udp', 'spmp', 'SPMP', 0),
(0, 657, 'tcp', 'rmc', 'RMC', 0),
(0, 657, 'udp', 'rmc', 'RMC', 0),
(0, 658, 'tcp', 'tenfold', 'TenFold', 0),
(0, 658, 'udp', 'tenfold', 'TenFold', 0),
(0, 659, 'tcp', 'url-rendezvous', 'URL Rendezvous', 0),
(0, 659, 'udp', 'url-rendezvous', 'URL Rendezvous', 0),
(0, 660, 'tcp', 'mac-srvr-admin', 'MacOS Server Admin', 0),
(0, 660, 'udp', 'mac-srvr-admin', 'MacOS Server Admin', 0),
(0, 661, 'tcp', 'hap', 'HAP', 0),
(0, 661, 'udp', 'hap', 'HAP', 0),
(0, 661, 'tcp', 'NokNok', 'NokNok', 1),
(0, 662, 'tcp', 'pftp', 'PFTP', 0),
(0, 662, 'udp', 'pftp', 'PFTP', 0),
(0, 663, 'tcp', 'purenoise', 'PureNoise', 0),
(0, 663, 'udp', 'purenoise', 'PureNoise', 0),
(0, 664, 'tcp', 'asf-secure-rcmp', 'ASF Secure Remote Management and Control Protocol', 0),
(0, 664, 'udp', 'asf-secure-rcmp', 'ASF Secure Remote Management and Control Protocol', 0),
(0, 664, 'tcp', 'secure-aux-bus', 'Secure Aux Bus', 0),
(0, 664, 'udp', 'secure-aux-bus', 'Secure Aux Bus', 0),
(0, 665, 'tcp', 'sun-dr', 'Sun DR', 0),
(0, 665, 'udp', 'sun-dr', 'Sun DR', 0),
(0, 666, 'tcp', 'mdqs', 'mdqs', 0),
(0, 666, 'udp', 'mdqs', 'mdqs', 0),
(0, 666, 'tcp', 'doom', 'doom Id Software', 0),
(0, 666, 'udp', 'doom', 'doom Id Software', 0),
(0, 666, 'tcp', 'AttackFTP', 'Attack FTP', 1),
(0, 666, 'tcp', 'BackConstruction', 'Back Construction', 1),
(0, 666, 'tcp', 'BLAtrojan', 'BLA trojan', 1),
(0, 666, 'tcp', 'Cain&Abel', 'Cain & Abel', 1),
(0, 666, 'tcp', 'lpdw0rm', 'lpdw0rm', 1),
(0, 666, 'tcp', 'NokNok', 'NokNok', 1),
(0, 666, 'tcp', 'SatansBackDoor', 'Satans Back Door - SBD', 1),
(0, 666, 'tcp', 'ServU', 'ServU', 1),
(0, 666, 'tcp', 'ShadowPhyre', 'Shadow Phyre', 1),
(0, 666, 'tcp', 'th3r1pp3rz', 'th3r1pp3rz (= Therippers)', 1),
(0, 667, 'tcp', 'disclose', 'campaign contribution disclosures - SDR Technologi', 0),
(0, 667, 'udp', 'disclose', 'campaign contribution disclosures - SDR Technologi', 0),
(0, 667, 'tcp', 'SniperNet', 'SniperNet', 1),
(0, 668, 'tcp', 'mecomm', 'MeComm', 0),
(0, 668, 'udp', 'mecomm', 'MeComm', 0),
(0, 668, 'tcp', 'th3r1pp3rz', 'th3r1pp3rz (= Therippers)', 1),
(0, 669, 'tcp', 'meregister', 'MeRegister', 0),
(0, 669, 'udp', 'meregister', 'MeRegister', 0),
(0, 669, 'tcp', 'DPtrojan', 'DP trojan', 1),
(0, 670, 'tcp', 'vacdsm-sws', 'VACDSM-SWS', 0),
(0, 670, 'udp', 'vacdsm-sws', 'VACDSM-SWS', 0),
(0, 671, 'tcp', 'vacdsm-app', 'VACDSM-APP', 0),
(0, 671, 'udp', 'vacdsm-app', 'VACDSM-APP', 0),
(0, 672, 'tcp', 'vpps-qua', 'VPPS-QUA', 0),
(0, 672, 'udp', 'vpps-qua', 'VPPS-QUA', 0),
(0, 673, 'tcp', 'cimplex', 'CIMPLEX', 0),
(0, 673, 'udp', 'cimplex', 'CIMPLEX', 0),
(0, 674, 'tcp', 'acap', 'ACAP', 0),
(0, 674, 'udp', 'acap', 'ACAP', 0),
(0, 675, 'tcp', 'dctp', 'DCTP', 0),
(0, 675, 'udp', 'dctp', 'DCTP', 0),
(0, 676, 'tcp', 'vpps-via', 'VPPS Via', 0),
(0, 676, 'udp', 'vpps-via', 'VPPS Via', 0),
(0, 677, 'tcp', 'vpp', 'Virtual Presence Protocol', 0),
(0, 677, 'udp', 'vpp', 'Virtual Presence Protocol', 0),
(0, 678, 'tcp', 'ggf-ncp', 'GNU Gereration Foundation NCP', 0),
(0, 678, 'udp', 'ggf-ncp', 'GNU Generation Foundation NCP', 0),
(0, 679, 'tcp', 'mrm', 'MRM', 0),
(0, 679, 'udp', 'mrm', 'MRM', 0),
(0, 680, 'tcp', 'entrust-aaas', 'entrust-aaas', 0),
(0, 680, 'udp', 'entrust-aaas', 'entrust-aaas', 0),
(0, 681, 'tcp', 'entrust-aams', 'entrust-aams', 0),
(0, 681, 'udp', 'entrust-aams', 'entrust-aams', 0),
(0, 682, 'tcp', 'xfr', 'XFR', 0),
(0, 682, 'udp', 'xfr', 'XFR', 0),
(0, 683, 'tcp', 'corba-iiop', 'CORBA IIOP', 0),
(0, 683, 'udp', 'corba-iiop', 'CORBA IIOP', 0),
(0, 684, 'tcp', 'corba-iiop-ssl', 'CORBA IIOP SSL', 0),
(0, 684, 'udp', 'corba-iiop-ssl', 'CORBA IIOP SSL', 0),
(0, 685, 'tcp', 'mdc-portmapper', 'MDC Port Mapper', 0),
(0, 685, 'udp', 'mdc-portmapper', 'MDC Port Mapper', 0),
(0, 686, 'tcp', 'hcp-wismar', 'Hardware Control Protocol Wismar', 0),
(0, 686, 'udp', 'hcp-wismar', 'Hardware Control Protocol Wismar', 0),
(0, 687, 'tcp', 'asipregistry', 'asipregistry', 0),
(0, 687, 'udp', 'asipregistry', 'asipregistry', 0),
(0, 688, 'tcp', 'realm-rusd', 'REALM-RUSD', 0),
(0, 688, 'udp', 'realm-rusd', 'REALM-RUSD', 0),
(0, 689, 'tcp', 'nmap', 'NMAP', 0),
(0, 689, 'udp', 'nmap', 'NMAP', 0),
(0, 689, 'tcp', 'SLDAP', 'LDAP over SSL', 0),
(0, 690, 'tcp', 'vatp', 'VATP', 0),
(0, 690, 'udp', 'vatp', 'VATP', 0),
(0, 691, 'tcp', 'msexch-routing', 'MS Exchange Routing', 0),
(0, 691, 'udp', 'msexch-routing', 'MS Exchange Routing', 0),
(0, 692, 'tcp', 'hyperwave-isp', 'Hyperwave-ISP', 0),
(0, 692, 'udp', 'hyperwave-isp', 'Hyperwave-ISP', 0),
(0, 692, 'tcp', 'GayOL', 'GayOL', 1),
(0, 693, 'tcp', 'connendp', 'connendp', 0),
(0, 693, 'udp', 'connendp', 'connendp', 0),
(0, 694, 'tcp', 'ha-cluster', 'ha-cluster', 0),
(0, 694, 'udp', 'ha-cluster', 'ha-cluster', 0),
(0, 695, 'tcp', 'ieee-mms-ssl', 'IEEE-MMS-SSL', 0),
(0, 695, 'udp', 'ieee-mms-ssl', 'IEEE-MMS-SSL', 0),
(0, 696, 'tcp', 'rushd', 'RUSHD', 0),
(0, 696, 'udp', 'rushd', 'RUSHD', 0),
(0, 697, 'tcp', 'uuidgen', 'UUIDGEN', 0),
(0, 697, 'udp', 'uuidgen', 'UUIDGEN', 0),
(0, 698, 'tcp', 'olsr', 'OLSR', 0),
(0, 698, 'udp', 'olsr', 'OLSR', 0),
(0, 699, 'tcp', 'accessnetwork', 'Access Network', 0),
(0, 699, 'udp', 'accessnetwork', 'Access Network', 0),
(0, 700, 'tcp', 'epp', 'Extensible Provisioning Protocol', 0),
(0, 700, 'udp', 'epp', 'Extensible Provisioning Protocol', 0),
(0, 701, 'tcp', 'lmp', 'Link Management Protocol (LMP)', 0),
(0, 701, 'udp', 'lmp', 'Link Management Protocol (LMP)', 0),
(0, 704, 'tcp', 'elcsd', 'errlog copy server daemon', 0),
(0, 704, 'udp', 'elcsd', 'errlog copy server daemon', 0),
(0, 705, 'tcp', 'agentx', 'AgentX', 0),
(0, 705, 'udp', 'agentx', 'AgentX', 0),
(0, 706, 'tcp', 'silc', 'SILC', 0),
(0, 706, 'udp', 'silc', 'SILC', 0),
(0, 707, 'tcp', 'borland-dsj', 'Borland DSJ', 0),
(0, 707, 'udp', 'borland-dsj', 'Borland DSJ', 0),
(0, 709, 'tcp', 'entrust-kmsh', 'Entrust Key Management Service Handler', 0),
(0, 709, 'udp', 'entrust-kmsh', 'Entrust Key Management Service Handler', 0),
(0, 710, 'tcp', 'entrust-ash', 'Entrust Administration Service Handler', 0),
(0, 710, 'udp', 'entrust-ash', 'Entrust Administration Service Handler', 0),
(0, 711, 'tcp', 'cisco-tdp', 'Cisco TDP', 0),
(0, 711, 'udp', 'cisco-tdp', 'Cisco TDP', 0),
(0, 712, 'tcp', 'tbrpf', 'TBRPF', 0),
(0, 712, 'udp', 'tbrpf', 'TBRPF', 0),
(0, 729, 'tcp', 'netviewdm1', 'IBM NetView DM 6000 Server/Client', 0),
(0, 729, 'udp', 'netviewdm1', 'IBM NetView DM 6000 Server/Client', 0),
(0, 730, 'tcp', 'netviewdm2', 'IBM NetView DM 6000 send/tcp', 0),
(0, 730, 'udp', 'netviewdm2', 'IBM NetView DM 6000 send/tcp', 0),
(0, 731, 'tcp', 'netviewdm3', 'IBM NetView DM 6000 receive/tcp', 0),
(0, 731, 'udp', 'netviewdm3', 'IBM NetView DM 6000 receive/tcp', 0),
(0, 737, 'udp', 'sometimes-rpc2', 'Rusersd on my OpenBSD box', 0),
(0, 740, 'tcp', 'netcp', 'NETscout Control Protocol', 0),
(0, 740, 'udp', 'netcp', 'NETscout Control Protocol', 0),
(0, 741, 'tcp', 'netgw', 'netGW', 0),
(0, 741, 'udp', 'netgw', 'netGW', 0),
(0, 742, 'tcp', 'netrcs', 'Network based Rev Cont Sys', 0),
(0, 742, 'udp', 'netrcs', 'Network based Rev Cont Sys', 0),
(0, 744, 'tcp', 'flexlm', 'Flexible License Manager', 0),
(0, 744, 'udp', 'flexlm', 'Flexible License Manager', 0),
(0, 747, 'tcp', 'fujitsu-dev', 'Fujitsu Device Control', 0),
(0, 747, 'udp', 'fujitsu-dev', 'Fujitsu Device Control', 0),
(0, 748, 'tcp', 'ris-cm', 'Russell Info Sci Calendar Manager', 0),
(0, 748, 'udp', 'ris-cm', 'Russell Info Sci Calendar Manager', 0),
(0, 749, 'tcp', 'kerberos-adm', 'Kerberos administration', 0),
(0, 749, 'udp', 'kerberos-adm', 'Kerberos administration', 0),
(0, 750, 'tcp', 'kerberos-iv', 'Kerberos v4', 0),
(0, 750, 'udp', 'kerberos-iv', 'Kerberos v4', 0),
(0, 750, 'tcp', 'rfile', 'rfile', 0),
(0, 750, 'udp', 'loadav', 'loadav', 0),
(0, 751, 'tcp', 'pump', 'pump', 0),
(0, 751, 'udp', 'pump', 'pump', 0),
(0, 751, 'tcp', 'kerberos_master', 'Kerberos `kadmin (v4)', 0),
(0, 751, 'udp', 'kerberos_master', 'Kerberos `kadmin (v4)', 0),
(0, 752, 'tcp', 'qrh', 'qrh', 0),
(0, 752, 'udp', 'qrh', 'qrh', 0),
(0, 753, 'tcp', 'rrh', 'rrh', 0),
(0, 753, 'udp', 'rrh', 'rrh', 0),
(0, 754, 'tcp', 'tell', 'send', 0),
(0, 754, 'udp', 'tell', 'send', 0),
(0, 754, 'tcp', 'krb_prop', 'kerberos v5 server propagation', 0),
(0, 758, 'tcp', 'nlogin', 'nlogin', 0),
(0, 758, 'udp', 'nlogin', 'nlogin', 0),
(0, 759, 'tcp', 'con', 'con', 0),
(0, 759, 'udp', 'con', 'con', 0),
(0, 760, 'tcp', 'ns', 'ns', 0),
(0, 760, 'udp', 'ns', 'ns', 0),
(0, 760, 'tcp', 'krbupdate', 'kreg Kerberos (v4) registration', 0),
(0, 761, 'tcp', 'rxe', 'rxe', 0),
(0, 761, 'udp', 'rxe', 'rxe', 0),
(0, 761, 'tcp', 'kpasswd', 'kpwd Kerberos (v4) passwd', 0),
(0, 762, 'tcp', 'quotad', 'quotad', 0),
(0, 762, 'udp', 'quotad', 'quotad', 0),
(0, 763, 'tcp', 'cycleserv', 'cycleserv', 0),
(0, 763, 'udp', 'cycleserv', 'cycleserv', 0),
(0, 764, 'tcp', 'omserv', 'omserv', 0),
(0, 764, 'udp', 'omserv', 'omserv', 0),
(0, 765, 'tcp', 'webster', 'webster', 0),
(0, 765, 'udp', 'webster', 'webster', 0),
(0, 767, 'tcp', 'phonebook', 'phonebook', 0),
(0, 767, 'udp', 'phonebook', 'phonebook', 0),
(0, 769, 'tcp', 'vid', 'vid', 0),
(0, 769, 'udp', 'vid', 'vid', 0),
(0, 770, 'tcp', 'cadlock', 'cadlock', 0),
(0, 770, 'udp', 'cadlock', 'cadlock', 0),
(0, 771, 'tcp', 'rtip', 'rtip', 0),
(0, 771, 'udp', 'rtip', 'rtip', 0),
(0, 772, 'tcp', 'cycleserv2', 'cycleserv2', 0),
(0, 772, 'udp', 'cycleserv2', 'cycleserv2', 0),
(0, 773, 'tcp', 'submit', 'submit', 0),
(0, 773, 'udp', 'notify', 'notify', 0),
(0, 774, 'tcp', 'rpasswd', 'rpasswd', 0),
(0, 774, 'udp', 'acmaint_dbd', 'acmaint_dbd', 0),
(0, 775, 'tcp', 'entomb', 'entomb', 0),
(0, 775, 'udp', 'acmaint_transd', 'acmaint_transd', 0),
(0, 776, 'tcp', 'wpages', 'wpages', 0),
(0, 776, 'udp', 'wpages', 'wpages', 0),
(0, 777, 'tcp', 'multiling-http', 'Multiling HTTP', 0),
(0, 777, 'udp', 'multiling-http', 'Multiling HTTP', 0),
(0, 777, 'tcp', 'AimSpy', 'AimSpy', 1),
(0, 777, 'tcp', 'Undetected', 'Undetected', 1),
(0, 780, 'tcp', 'wpgs', 'wpgs', 0),
(0, 780, 'udp', 'wpgs', 'wpgs', 0),
(0, 781, 'tcp', 'hp-collector', 'hp performance data collector', 0),
(0, 781, 'udp', 'hp-collector', 'hp performance data collector', 0),
(0, 782, 'tcp', 'hp-managed-node', 'hp performance data managed node', 0),
(0, 782, 'udp', 'hp-managed-node', 'hp performance data managed node', 0),
(0, 783, 'tcp', 'hp-alarm-mgr', 'hp performance data alarm manager', 0),
(0, 783, 'udp', 'hp-alarm-mgr', 'hp performance data alarm manager', 0),
(0, 786, 'tcp', 'concert', 'concert', 0),
(0, 786, 'udp', 'concert', 'concert', 0),
(0, 787, 'tcp', 'qsc', 'QSC', 0),
(0, 787, 'udp', 'qsc', 'QSC', 0),
(0, 799, 'tcp', 'controlit', 'controlit', 0),
(0, 800, 'tcp', 'mdbs_daemon', 'mdbs_daemon', 0),
(0, 800, 'udp', 'mdbs_daemon', 'mdbs_daemon', 0),
(0, 801, 'tcp', 'device', 'device', 0),
(0, 801, 'udp', 'device', 'device', 0),
(0, 808, 'tcp', 'WinHole', 'WinHole', 1),
(0, 810, 'tcp', 'fcp-udp', 'FCP', 0),
(0, 810, 'udp', 'fcp-udp', 'FCP Datagram', 0),
(0, 828, 'tcp', 'itm-mcell-s', 'itm-mcell-s', 0),
(0, 828, 'udp', 'itm-mcell-s', 'itm-mcell-s', 0),
(0, 829, 'tcp', 'pkix-3-ca-ra', 'PKIX-3 CA RA', 0),
(0, 829, 'udp', 'pkix-3-ca-ra', 'PKIX-3 CA RA', 0),
(0, 847, 'tcp', 'dhcp-failover2', 'dhcp-failover 2', 0),
(0, 847, 'udp', 'dhcp-failover2', 'dhcp-failover 2', 0),
(0, 848, 'tcp', 'gdoi', 'GDOI', 0),
(0, 848, 'udp', 'gdoi', 'GDOI', 0),
(0, 860, 'tcp', 'iscsi', 'iSCSI', 0),
(0, 860, 'udp', 'iscsi', 'iSCSI', 0),
(0, 871, 'tcp', 'supfilesrv', 'SUP server', 0),
(0, 873, 'tcp', 'rsync', 'rsync', 0),
(0, 873, 'udp', 'rsync', 'rsync', 0),
(0, 886, 'tcp', 'iclcnet-locate', 'ICL coNETion locate server', 0),
(0, 886, 'udp', 'iclcnet-locate', 'ICL coNETion locate server', 0),
(0, 887, 'tcp', 'iclcnet_svinfo', 'ICL coNETion server info', 0),
(0, 887, 'udp', 'iclcnet_svinfo', 'ICL coNETion server info', 0),
(0, 888, 'tcp', 'accessbuilder', 'AccessBuilder', 0),
(0, 888, 'udp', 'accessbuilder', 'AccessBuilder', 0),
(0, 888, 'tcp', 'cddbp', 'CD Database Protocol', 0),
(0, 900, 'tcp', 'omginitialrefs', 'OMG Initial Refs', 0),
(0, 900, 'udp', 'omginitialrefs', 'OMG Initial Refs', 0),
(0, 900, 'tcp', 'fw1-clntauth-http', 'Check Point FW-1/VPN-1 client auth (http)', 0),
(0, 901, 'tcp', 'samba-swat', 'Samba SWAT tool', 0),
(0, 901, 'tcp', 'realsecure', 'RealSecure sensor', 0),
(0, 901, 'tcp', 'smpnameres', 'SMPNAMERES', 0),
(0, 901, 'udp', 'smpnameres', 'SMPNAMERES', 0),
(0, 902, 'tcp', 'ideafarm-chat', 'IDEAFARM-CHAT', 0),
(0, 902, 'udp', 'ideafarm-chat', 'IDEAFARM-CHAT', 0),
(0, 903, 'tcp', 'ideafarm-catch', 'IDEAFARM-CATCH', 0),
(0, 903, 'udp', 'ideafarm-catch', 'IDEAFARM-CATCH', 0),
(0, 911, 'tcp', 'xact-backup', 'xact-backup', 0),
(0, 911, 'udp', 'xact-backup', 'xact-backup', 0),
(0, 911, 'tcp', 'DarkShadow', 'Dark Shadow', 1),
(0, 912, 'tcp', 'apex-mesh', 'APEX relay-relay service', 0),
(0, 912, 'udp', 'apex-mesh', 'APEX relay-relay service', 0),
(0, 913, 'tcp', 'apex-edge', 'APEX endpoint-relay service', 0),
(0, 913, 'udp', 'apex-edge', 'APEX endpoint-relay service', 0),
(0, 953, 'tcp', 'rndc', 'BIND 9 rndc control socket', 0),
(0, 953, 'udp', 'rndc', 'BIND 9 rndc control socket (NOTUSED)', 0),
(0, 974, 'tcp', 'securenetpro', 'SecureNet Pro secure comm to console', 0),
(0, 975, 'tcp', 'securenetpro', 'SecureNet Pro sensor', 0),
(0, 989, 'tcp', 'ftps-data', 'ftp data over TLS/SSL', 0),
(0, 989, 'udp', 'ftps-data', 'ftp data over TLS/SSL', 0),
(0, 990, 'tcp', 'ftps', 'ftp data over TLS/SSL', 0),
(0, 990, 'udp', 'ftps', 'ftp data over TLS/SSL', 0),
(0, 991, 'tcp', 'nas', 'Netnews Administration System', 0),
(0, 991, 'udp', 'nas', 'Netnews Administration System', 0),
(0, 992, 'tcp', 'telnets', 'telnet protocol over TLS/SSL', 0),
(0, 992, 'udp', 'telnets', 'telnet protocol over TLS/SSL', 0),
(0, 993, 'tcp', 'imaps', 'imap4 protocol over TLS/SSL', 0),
(0, 993, 'udp', 'imaps', 'imap4 protocol over TLS/SSL', 0),
(0, 994, 'tcp', 'ircs', 'irc protocol over TLS/SSL', 0),
(0, 994, 'udp', 'ircs', 'irc protocol over TLS/SSL', 0),
(0, 995, 'tcp', 'pop3s', 'POP3 protocol over TLS/SSL', 0),
(0, 995, 'udp', 'pop3s', 'pop3 protocol over TLS/SSL (was spop3)', 0),
(0, 996, 'tcp', 'vsinet', 'vsinet', 0),
(0, 996, 'udp', 'vsinet', 'vsinet', 0),
(0, 996, 'tcp', 'xtreelic', 'XTREE License Server', 0),
(0, 997, 'tcp', 'maitrd', 'maitrd', 0),
(0, 997, 'udp', 'maitrd', 'maitrd', 0),
(0, 998, 'tcp', 'busboy', 'busboy', 0),
(0, 998, 'udp', 'puparp', 'puparp', 0),
(0, 999, 'tcp', 'garcon', 'garcon', 0),
(0, 999, 'udp', 'applix', 'Applix ac', 0),
(0, 999, 'tcp', 'puprouter', 'puprouter', 0),
(0, 999, 'udp', 'puprouter', 'puprouter', 0),
(0, 999, 'tcp', 'Chatpower', 'Chat power', 1),
(0, 999, 'tcp', 'DeepThroat', 'DeepThroat', 1),
(0, 999, 'tcp', 'Foreplay', 'Foreplay', 1),
(0, 999, 'tcp', 'WinSatan', 'WinSatan', 1),
(0, 1000, 'tcp', 'cadlock2', 'cadlock2', 0),
(0, 1000, 'udp', 'cadlock2', 'cadlock2', 0),
(0, 1000, 'tcp', 'Connecter', 'Connecter', 1),
(0, 1000, 'tcp', 'DerSpaeher', 'Der Spaeher / Der Spaeher', 1),
(0, 1000, 'tcp', 'DerSpherDerSpaeher', 'Der Spaeher / Der Spaeher', 1),
(0, 1000, 'tcp', 'DirectConnection', 'Direct Connection', 1),
(0, 1000, 'tcp', 'InsaneNetwork', 'Insane Network', 1),
(0, 1001, 'tcp', 'sabserv', 'Sabre Desktop Reservation Software for Windows', 0),
(0, 1001, 'tcp', 'DerSpaeher', 'Der Spaeher / Der Spaeher', 1),
(0, 1001, 'tcp', 'LeGuardien', 'Le Guardien', 1),
(0, 1001, 'tcp', 'Silencer', 'Silencer', 1),
(0, 1001, 'tcp', 'Theef', 'Theef', 1),
(0, 1001, 'tcp', 'WebEx', 'WebEx', 1),
(0, 1002, 'tcp', 'win2k-ils', 'Microsoft NetMeeting ILS server default port (win2', 0),
(0, 1005, 'tcp', 'Theef', 'Theef', 1),
(0, 1008, 'tcp', 'Lion', 'Lion', 1),
(0, 1008, 'tcp', 'ufsd', 'ufsd UFS-aware server', 0),
(0, 1008, 'udp', 'ufsd', 'ufsd UFS-aware server', 0),
(0, 1008, 'udp', 'Possibly used by Sun Solaris????', 'Possibly used by Sun Solaris????', 0),
(0, 1010, 'tcp', 'surf', 'surf', 0),
(0, 1010, 'udp', 'surf', 'surf', 0),
(0, 1010, 'tcp', 'DolyTrojan', 'Doly Trojan', 1),
(0, 1011, 'tcp', 'DolyTrojan', 'Doly Trojan', 1),
(0, 1012, 'udp', 'sometimes-rpc1', 'This is rstatd on my openBSD box box', 0),
(0, 1012, 'tcp', 'DolyTrojan', 'Doly Trojan', 1),
(0, 1015, 'tcp', 'DolyTrojan', 'Doly Trojan', 1),
(0, 1016, 'tcp', 'DolyTrojan', 'Doly Trojan', 1),
(0, 1020, 'tcp', 'Vampire', 'Vampire', 1),
(0, 1023, 'tcp', 'gs400-nas', 'Linux backend of Gateway GS-400 NAS', 0),
(0, 1024, 'tcp', 'kdm', 'K Display Manager (KDE version of xdm) xdm)', 0),
(0, 1024, 'tcp', 'Jade', 'Jade', 1),
(0, 1024, 'tcp', 'Latinus', 'Latinus', 1),
(0, 1024, 'tcp', 'NetSpy', 'NetSpy', 1),
(0, 1024, 'tcp', 'RAT', 'Remote Administration Tool - RAT [no 2]', 1);";
            $result =& $dbconn->Execute($query);
            xarResponseRedirect(xarModURL('netquery', 'admin', 'xaports', array('step' => '2', 'phase' => 'display')));
            return true;
            exit;
            break;
        case '2-display':
            $data['body'] = '<br /><br />A new ports table has been created and populated with services and exploits data up to port number 1024.';
            $data['body'] .= '<br /><br />Do you wish to populate higher ports?:';
            $data['body'] .= ' [<a href="'.xarModURL('netquery', 'admin', 'xaports', array('step' => '2', 'phase' => 'update')).'">Yes</a>]';
            $data['body'] .= ' [<a href="'.xarModURL('netquery', 'admin', 'config').'">No</a>]<br /><br />';
            break;
        case '2-update':
            xarResponseRedirect(xarModURL('netquery', 'admin', 'xaports2', array('step' => '3', 'phase' => 'update')));
            return true;
            exit;
            break;
        case '3-display':
            $data['body'] = '<br /><br />Process completed. The new ports table has now been populated with services and exploits data up to port number 65535.';
            $data['body'] .= '<br /><br />Please click <a href="'.xarModURL('netquery', 'admin', 'config').'">HERE</a> to return to Netquery\'s main admin panel.<br /><br />';
            break;
    }
    return $data;
}
?>