<?php
/**
 * Dossier Module
 *
 * @package modules
 * @copyright (C) 2002-2007 Chad Kraeft
 * @license GPL {@link http://www.gnu.org/licenses/gpl.html}
 * @link http://www.xaraya.com
 *
 * @subpackage Dossier Module
 * @link http://xaraya.com/index.php/release/829.html
 * @author St.Ego <webmaster@ivory-tower.net>
 */
/**
 * Update an example item
 *
 * @author the Example module development team
 * @param  $args ['exid'] the ID of the item
 * @param  $args ['name'] the new name of the item
 * @param  $args ['number'] the new number of the item
 * @raise BAD_PARAM, NO_PERMISSION, DATABASE_ERROR
 */
function dossier_adminapi_fixcountries($args)
{
    extract($args);
    
    if (!xarSecurityCheck('TeamAccess', 1, 'Item', "All:All:All")) {
        return;
    }
    
    $country_list = array('af'=>"Afghanistan",  
			'ax'=>"&#197;land Islands",  
			'al'=>"Albania",  
			'dz'=>"Algeria",  
			'as'=>"American Samoa",  
			'ad'=>"Andorra",  
			'ao'=>"Angola",  
			'ai'=>"Anguilla",  
			'aq'=>"Antarctica",  
			'ag'=>"Antigua and Barbuda",  
			'ar'=>"Argentina",  
			'am'=>"Armenia",  
			'aw'=>"Aruba",  
			'au'=>"Australia",  
			'at'=>"Austria",  
			'az'=>"Azerbaijan",  
			'bs'=>"Bahamas",  
			'bh'=>"Bahrain",  
			'bd'=>"Bangladesh",  
			'bb'=>"Barbados",  
			'by'=>"Belarus",  
			'be'=>"Belgium",  
			'bz'=>"Belize",  
			'bj'=>"Benin",  
			'bm'=>"Bermuda",  
			'bt'=>"Bhutan",  
			'bo'=>"Bolivia",  
			'ba'=>"Bosnia and Herzegovina",  
			'bw'=>"Botswana",  
			'bv'=>"Bouvet Island",  
			'br'=>"Brazil",  
			'io'=>"British Indian Ocean Territory",  
			'bn'=>"Brunei Darussalam",  
			'bg'=>"Bulgaria",  
			'bf'=>"Burkina Faso",  
			'bi'=>"Burundi",  
			'kh'=>"Cambodia",  
			'cm'=>"Cameroon",  
			'ca'=>"Canada",  
			'cv'=>"Cape Verde",  
			'ky'=>"Cayman Islands",  
			'cf'=>"Central African Republic",  
			'td'=>"Chad",  
			'cl'=>"Chile",  
			'cn'=>"China",  
			'cx'=>"Christmas Island",  
			'cc'=>"Cocos (Keeling) Islands",  
			'co'=>"Colombia",  
			'km'=>"Comoros",  
			'cg'=>"Congo, Republic of",  
			'cd'=>"Congo, Democratic Republic of (Zaire)",  
			'ck'=>"Cook Islands",  
			'cr'=>"Costa Rica",  
			'ci'=>"C&#244;te D'Ivoire",  
			'hr'=>"Croatia",  
			'cu'=>"Cuba",  
			'cy'=>"Cyprus",  
			'cz'=>"Czech Republic",  
			'dk'=>"Denmark",  
			'dj'=>"Djibouti",  
			'dm'=>"Dominica",  
			'do'=>"Dominican Republic",  
			'ec'=>"Ecuador",  
			'eg'=>"Egypt",  
			'sv'=>"El Salvador",  
			'gq'=>"Equatorial Guinea",  
			'er'=>"Eritrea",  
			'ee'=>"Estonia",  
			'et'=>"Ethiopia",  
			'fk'=>"Falkland Islands (Malvinas)",  
			'fo'=>"Faroe Islands",  
			'fj'=>"Fiji",  
			'fi'=>"Finland",  
			'fr'=>"France",  
			'gf'=>"French Guiana",  
			'pf'=>"French Polynesia",  
			'tf'=>"French Southern Territories",  
			'ga'=>"Gabon",  
			'gm'=>"Gambia",  
			'ge'=>"Georgia",  
			'de'=>"Germany",  
			'gh'=>"Ghana",  
			'gi'=>"Gibraltar",  
			'gr'=>"Greece",  
			'gl'=>"Greenland",  
			'gd'=>"Grenada",  
			'gp'=>"Guadeloupe",  
			'gu'=>"Guam",  
			'gt'=>"Guatemala",  
			'gn'=>"Guinea",  
			'gw'=>"Guinea-Bissau",  
			'gy'=>"Guyana",  
			'ht'=>"Haiti",  
			'hm'=>"Heard Island &#38; McDonald Islands",  
			'hn'=>"Honduras",  
			'hk'=>"Hong Kong",  
			'hu'=>"Hungary",  
			'is'=>"Iceland",  
			'in'=>"India",  
			'id'=>"Indonesia",  
			'ir'=>"Iran",  
			'iq'=>"Iraq",  
			'ie'=>"Ireland",  
			'il'=>"Israel",  
			'it'=>"Italy",  
			'jm'=>"Jamaica",  
			'jp'=>"Japan",  
			'jo'=>"Jordan",  
			'kz'=>"Kazakhstan",  
			'ke'=>"Kenya",  
			'ki'=>"Kiribati",  
			'kp'=>"Korea, Democratic People's Republic",  
			'kr'=>"Korea, Republic of",  
			'kw'=>"Kuwait",  
			'kg'=>"Kyrgyzstan",  
			'la'=>"Lao People's Democratic Republic",  
			'lv'=>"Latvia",  
			'lb'=>"Lebanon",  
			'ls'=>"Lesotho",  
			'lr'=>"Liberia",  
			'ly'=>"Libya",  
			'li'=>"Liechtenstein",  
			'lt'=>"Lithuania",  
			'lu'=>"Luxembourg",  
			'mo'=>"Macao",  
			'mk'=>"Macedonia, The Former Yugoslav Republic of",  
			'mg'=>"Madagascar",  
			'mw'=>"Malawi",  
			'my'=>"Malaysia",  
			'mv'=>"Maldives",  
			'ml'=>"Mali",  
			'mt'=>"Malta",  
			'mh'=>"Marshall Islands",  
			'mq'=>"Martinique",  
			'mr'=>"Mauritania",  
			'mu'=>"Mauritius",  
			'yt'=>"Mayotte",  
			'mx'=>"Mexico",  
			'fm'=>"Micronesia, Federated States of",  
			'md'=>"Moldova, Republic of",  
			'mc'=>"Monaco",  
			'mn'=>"Mongolia",  
			'ms'=>"Montserrat",  
			'ma'=>"Morocco",  
			'mz'=>"Mozambique",  
			'mm'=>"Myanmar",  
			'na'=>"Namibia",  
			'nr'=>"Nauru",  
			'np'=>"Nepal",  
			'nl'=>"Netherlands",  
			'an'=>"Netherlands Antilles",  
			'nc'=>"New Caledonia",  
			'nz'=>"New Zealand",  
			'ni'=>"Nicaragua",  
			'ne'=>"Niger",  
			'ng'=>"Nigeria",  
			'nu'=>"Niue",  
			'nf'=>"Norfolk Island",  
			'mp'=>"Northern Mariana Islands",  
			'no'=>"Norway",  
			'om'=>"Oman",  
			'pk'=>"Pakistan",  
			'pw'=>"Palau",  
			'ps'=>"Palestinian Territory",  
			'pa'=>"Panama",  
			'pg'=>"Papua New Guinea",  
			'py'=>"Paraguay",  
			'pe'=>"Peru",  
			'ph'=>"Philippines",  
			'pn'=>"Pitcairn",  
			'pl'=>"Poland",  
			'pt'=>"Portugal",  
			'pr'=>"Puerto Rico",  
			'qa'=>"Qatar",  
			're'=>"R&#233;union",  
			'ro'=>"Romania",  
			'ru'=>"Russian Federation",  
			'rw'=>"Rwanda",  
			'sh'=>"St. Helena",  
			'kn'=>"St. Kitts and Nevis",  
			'lc'=>"St. Lucia",  
			'pm'=>"St. Pierre and Miquelon",  
			'vc'=>"St. Vincent and the Grenadines",  
			'ws'=>"Samoa",  
			'sm'=>"San Marino",  
			'st'=>"S&#227;o Tom&#233; and Pr&#237;ncipe",  
			'sa'=>"Saudi Arabia",  
			'sn'=>"Senegal",  
			'cs'=>"Serbia &#38; Montenegro",  
			'sc'=>"Seychelles",  
			'sl'=>"Sierra Leone",  
			'sg'=>"Singapore",  
			'sk'=>"Slovakia",  
			'si'=>"Slovenia",  
			'sb'=>"Solomon Islands",  
			'so'=>"Somalia",  
			'za'=>"South Africa",  
			'gs'=>"Sth Georgia &#38; the South Sandwich Islands",  
			'es'=>"Spain",  
			'lk'=>"Sri Lanka",  
			'sd'=>"Sudan",  
			'sr'=>"Suriname",  
			'sj'=>"Svalbard &#38; Jan Mayen",  
			'sz'=>"Swaziland",  
			'se'=>"Sweden",  
			'ch'=>"Switzerland",  
			'sy'=>"Syria",  
			'tw'=>"Taiwan",  
			'tj'=>"Tajikistan",  
			'tz'=>"Tanzania, United Republic of",  
			'th'=>"Thailand",  
			'tl'=>"Timor-Leste (East Timor)",  
			'tg'=>"Togo",  
			'tk'=>"Tokelau",  
			'to'=>"Tonga",  
			'tt'=>"Trinidad and Tobago",  
			'tn'=>"Tunisia",  
			'tr'=>"Turkey",  
			'tm'=>"Turkmenistan",  
			'tc'=>"Turks and Caicos Islands",  
			'tv'=>"Tuvalu",  
			'ug'=>"Uganda",  
			'ua'=>"Ukraine",  
			'ae'=>"United Arab Emirates",  
			'gb'=>"United Kingdom",  
			'us'=>"United States",  
			'um'=>"U.S. Minor Outlying Islands",  
			'uy'=>"Uruguay",  
			'uz'=>"Uzbekistan",  
			'vu'=>"Vanuatu",  
			'va'=>"Vatican City State (Holy See)",  
			've'=>"Venezuela",  
			'vn'=>"Vietnam",  
			'vg'=>"Virgin Islands, British",  
			'vi'=>"Virgin Islands, U.S.",  
			'wf'=>"Wallis &#38; Futuna",  
			'eh'=>"Western Sahara",  
			'ye'=>"Yemen",  
			'zm'=>"Zambia",  
			'zw'=>"Zimbabwe");
            
    $dbconn =& xarDBGetConn();
    $xartable =& xarDBGetTables();

    $locationstable = $xartable['dossier_locations'];

    $query = "UPDATE $locationstable
            SET country = LTRIM(country)";
              
    $result = &$dbconn->Execute($query);

    foreach($country_list as $abbrev => $country) {

        $query = "UPDATE $locationstable
                SET country = ?
                WHERE country = ?";
                
        $bindvars = array(
                  $abbrev,
                  $country);
                  
        $result = &$dbconn->Execute($query,$bindvars);
    }
    
    return true;
}
?>
