// SE lang variables

tinyMCE.addToLang({
table_desc : 'Skapa ny tabell',
table_insert_row_before_desc : 'Skapa rad f&ouml;re',
table_insert_row_after_desc : 'Skapa rad efter',
table_delete_row_desc : 'Ta bort rad',
table_insert_col_before_desc : 'Skapa kolumn f&ouml;re',
table_insert_col_after_desc : 'Skapa kolumn efter',
table_delete_col_desc : 'Ta bort kolumn',
insert_table_title : 'Skapa/Redigera tabell',
insert_table_width : 'Bredd',
insert_table_height : 'H&ouml;jd',
insert_table_cols : 'Kolumner',
insert_table_rows : 'Rader',
insert_table_cellspacing : 'Cellmellanrum',
insert_table_cellpadding : 'Cellutfyllnad',
insert_table_border : 'Rambredd',
insert_table_align : 'Justering',
insert_table_align_default : 'Ingen',
insert_table_align_left : 'V&auml;nster',
insert_table_align_right : 'H&ouml;ger',
insert_table_align_middle : 'Mitten',
insert_table_class : 'Stil',
table_row_title : 'Tabellradsinst&auml;llningar',
table_cell_title : 'Tabellcellsinst&auml;llningar',
table_row_desc : 'Tabellradsinst&auml;llningar',
table_cell_desc : 'Tabellcellsinst&auml;llningar',
insert_table_valign : 'Vertikal justering',
insert_table_align_top : 'Toppen',
insert_table_align_bottom : 'Botten',
table_props_desc : 'Tabell egenskaper',
table_bordercolor : 'Ramf&auml;rg',
table_bgcolor : 'Bakgrundsfärd',
table_merge_cells_title : 'Sammanfoga tabell celler',
table_split_cells_desc : 'Delaupp tabell celler',
table_merge_cells_desc : 'Sammanfoga tabell celler',
table_cut_row_desc : 'Klipput tabell rad',
table_copy_row_desc : 'Kopiera tabell rad',
table_paste_row_before_desc : 'Klistra in tabell rad f&ouml;re',
table_paste_row_after_desc : 'Klistra in tabell rad efter',
table_insert_desc : 'Insert a new table'
});
