<?php
$buttonarray = array(
     'Buttons' =>array(
                    'bold'          => array('bold'  ),
                    'italic'        =>array( 'italic' ),
                    'underline'     => array('underline'),
                    'strikethrough' =>array('strikethrough'  ),
                    'justifyleft'   =>array( 'justifyleft' ),
                    'justifyright'  =>array( 'justifyright' ),
                    'justifyfull'   =>array( 'justifyfull' ),
                    'bullist'   =>array('bullist'  ),
                    'numlist'   =>array( 'numlist' ),
                    'outdent'   =>array('outdent'  ),
                    'indent'    =>array( 'indent' ),
                    'cut'       =>array('cut'  ),
                    'copy'      =>array( 'copy' ),
                    'paste'     =>array( 'paste' ),
                    'undo'      =>array('undo'  ),
                    'redo'      =>array( 'redo' ),
                    'link'      =>array('link'  ),
                    'unlink'    =>array('unlink'   ),
                    'image'     =>array('image'  ),
                    'cleanup'   =>array( 'cleanup'  ),
                    'help'      =>array( 'help' ),
                    'code'      =>array('code'   ),
                    'hr'        =>array( 'hr'  ),
                    'removeformat'  =>array( 'removeformat' ),
                    'formatselect'  =>array('formatselect'  ),
                    'fontselect'    =>array( 'fontselect' ),
                    'fontsizeselect'=>array('fontsizeselect'  ),
                    'styleselect'   =>array( 'styleselect' ),
                    'styleselect'   =>array( 'styleselect'  ),
                    'sub'           =>array( 'sub' ),
                    'sup'           =>array( 'sup' ),
                    'forecolor'     =>array( 'forecolor' ),
                    'backcolor'     =>array('backcolor'   ),
                    'charmap'       =>array( 'charmap' ),
                    'visualaid'     =>array( 'visualaid'  ),
                    'anchor'        =>array( 'anchor' ),
                    'newdocument'   =>array('newdocument'  ),
                    'blockquote'    =>array('blockquote'  ),
                    'separator'     =>array('separator'  ),  
                ),
        
        'Plugins' =>array(
                'autosave'=> array('---'), 
                'advcode'=> array('advcode'),        
                'advhr'=> array('advhr'),
                'advimg'=> array('---'), 
                'advlink'=> array('---'),
                'advlist'=> array('---'),
                'directionality'=>array('ltr','rtl'),
                'dphighlight' => array('dphighlight'),                
                'emotions'=> array('emotions'),
                'flash'=> array('flash'),
                'fullpage'=> array('fullpage'),
                'fullscreen'=> array('fullscreen'),
                'ibrowser' => array('ibrowser'),
                'iespell'=> array('iespell'),                
                'imanager' => array('imanager'),
                'insertdatetime'=> array('insertdate','inserttime'), 
                'inlinepopups'=> array('---'),                   
                'layer' => array('moveforward','movebackward','absolute','insertlayer'), 
                'legacyoutput' => array('---'),                             
                'liststyle' => array('DEPRECATED-use advlist'), 
                'loremipsum' => array('loremipsum'),                                  
                'media'=> array('media'),
                'nonbreaking'=> array('nonbreaking'),
                'pagebreak'=> array('pagebreak'),
                'paste' => array('pastetext','pasteword','selectall'),                
                'preview' => array('preview'),
                'print'=> array('print'),
                'spellchecker'=> array('spellchecker'),
                'save' => array('save','cancel'),
                'safari' => array('---'),                                   
                'searchreplace' => array('search','replace'),
                'safari' => array('spellchecker'),                     
                'spellchecker'=>array('styleprops'),
                'table'=>array('tablecontrols','table','row_props','cell_props','delete_col','delete_row','col_after','col_before','row_after','row_before','split_cells','merge_cells'),
                'tabfocus' => array('tabfocus'),
                'tinybrowser'=>array('---'),
                'template'=> array('template'),
                'visualchars'=> array('visualchars'),
                'wordcount'=> array('---'),
                'xhtmlxtras' => array('cite','abbr','acronym','ins','del','attribs'),

                         ),
);  


?>