<?php
/**
   The main mailbag administration function
   This function is the default function, and is called whenever the
   module is initiated without defining arguments.
   
   @return template data
 */
function mailbag_admin_main()
{    
    if (!xarSecurityCheck('adminmailbag')) { return; }
    
    if (xarModGetVar('adminpanels', 'overview') == 0){
        $welcome = '';

        // Return the output that has been generated by this function
        return array('welcome' => $welcome);
    } else {
        // View the ticket object by default
        xarResponseRedirect(xarModURL('mailbag', 'admin', 'view', array('itemtype' => 1)));
    }
    // success
    return true;
}
?>
