<?php
/**
   This is a standard function to modify the configuration parameters of the
   module
   
   @return template data
*/
function mailbag_admin_modifyconfig()
{
    // Security check - important to do this as early as possible to avoid
    // potential security holes or just too much wasted processing
    if (!xarSecurityCheck('adminmailbag')) { return; }

    // Add menu to output - it helps if all of the module pages have a standard
    // menu at their head to aid in navigation
    //$data = xarModAPIFunc('mailbag', 'admin', 'menu');
    
    // Add an authorisation ID - this adds a hidden field in the form that
    // contains an authorisation ID.  The authorisation ID is very important in
    // preventing certain attacks on the website
    $data['enforceauthkey'] = xarModGetVar('mailbag', 'EnforceAuthKey');
    $data['authid'] = xarSecGenAuthKey();
   
    if (!xarVarFetch('itemtype', 'int', $itemtype, 1, XARVAR_NOT_REQUIRED)) return;
            
    $hooks = xarModCallHooks('module', 'modifyconfig', 'mailbag',
                            array('module'   => 'mailbag',
                                  'itemtype' => $itemtype)); 
    if (empty($hooks)) {
        $data['hooks'] = '';
    } elseif (is_array($hooks)) {
        $data['hooks'] = join('',$hooks);
    } else {
        $data['hooks'] = $hooks;
    }
    
    // Return the output that has been generated by this function
    return $data;
}
?>
