#!/bin/sh

# Run some sanity checks for php sourcefiles

STARTDIR=`bk root`

echo "Checking whole repository for php errors..."

for i in `bk sfiles -g $STARTDIR | grep "\.php"`; do
    bk get -qS $i
    errmsg=`php -q -l -f $i`
    if [ $? -ne 0 ]; then
      echo
      echo $errmsg
    else
      echo -n . 
    fi
done 
echo