#!/bin/sh

#
# This script is for running some of the code review tests for Xaraya. It is
# based on the Xaraya QA Code Review Checklist v0.1
# (http://www.ninthave.net/docs/81)
#
# Roger Keays <r.keays@ninthave.net>
# 05 Jan 2004
# 
# TODO: filter to only run template tests on .xd and .xt files
#


export BK_SIDE=server
export BK_RUNQA=yes

# Just run the trigger
`bk root`/BitKeeper/triggers/pre-apply.qa

# Use exit code of the trigger
exit $?
